#!/bin/bash

##
##      Download and store WP Engine snapshot on Dropbox
##
##      Pass arguments from command line like this
##      ah manage store_snapshot
##

# Load configuration
source ~/Scripts/config

read -p $'\e[31mWP Engine Download\e[0m: ' wpdownloadzip
wpdownloadzipfilename=`echo $wpdownloadzip | perl -n -e '/\/(site.+.zip)/&& print $1'`
wget $wpdownloadzip
$path_rclone/rclone move $wpdownloadzipfilename Anchor-Dropbox:Backup/Archive/ -v
