#!/usr/bin/env bash

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

cd ${root_path}data
wp core update
wp plugin update --all
wp eval 'CaptainCore\DB::upgrade();'

# Git update from server
cd ${root_path}
git pull

# Grant execute permissions
find ~/.captaincore-cli/app/ -type f -exec chmod +x {} \;
