#!/usr/bin/env bash

#
#   Fetches list of quicksaves for a site
#
#   `captaincore quicksave list <site>`
#

if [ ${#@} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Requires a <site>"
  exit
fi

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(php ${CAPTAINCORE_PATH}/lib/local-scripts/configs.php fetch)"

site=$1

run_command() {

  # Extract environment
  if [[ "$site" == *"-staging"* ]]; then
    environment=staging
  fi

  if [[ "$site" == *"-production"* ]]; then
    environment=production
  fi

  if [[ "$site" != *"-"* ]]; then
    environment=production
  fi

  # Load site configs
  while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain-id=$CAPTAIN_ID)"

  quicksave_list="$path/${site}_${site_id}/${environment}/quicksaves/list.json"
  if [ ! -f "$quicksave_list" ] || [[ $( stat --printf="%s" $quicksave_list ) == "0" ]]; then
    captaincore quicksave list-generate $site-$environment --captain-id=$CAPTAIN_ID
  fi
  cat "$quicksave_list"

}

run_command