#!/usr/bin/env bash

#
#   Lists environments for a site
#
#   `captaincore site environment list <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

# Remove leading "--" from flags
for i in "${!flags[@]}"; do
	flags[$i]=$( echo ${flags[$i]} | cut -c 3- )
done

cd ${root_path}data
wp eval-file ${root_path}lib/local-scripts/site-environment-list.php site=$1
