#!/bin/bash

##
##      Bulk domain output
##
##      Pass arguments from command line like this
##      captaincore dns bulk_domain website1.com website2.com website3.com
##
##			Expected output
##			website1.com	Registrar: Tucows Reseller: Hover.com
##			website2.com	Registrar: Tucows Reseller: Hover.com
##
lightblue='\033[0;34m'
nocolor='\033[0m' # No Color

for var in "$@"
do
	whois=`whois $var`
	registrar=`echo "$whois" | grep "Registrar:" | tr -d '\r' | xargs`
	reseller=`echo "$whois" | grep "Reseller:"| tr -d '\r' | xargs`
	result="${registrar} ${reseller}"
	echo -e "${lightblue}${var}${nocolor} - ${result}"
done
