#!/bin/zsh

##
##      Bulk nameserver output
##
##      Pass arguments from command line like this
##      captaincore dns bulk_nameservers website1.com website2.com website3.com
##
##			Expected output
##			website1.com	nameserver1.com, nameserver2.com, nameserver3.com
##			website2.com	nameserver1.com, nameserver2.com, nameserver3.com
##

lightblue='\033[0;34m'
nocolor='\033[0m' # No Color

for var in "$@"
do
	dnslookup=`dig $var NS +short`
	dnslookup_sorted=(`echo $dnslookup | sort -n`)
	echo -e "${lightblue}${var}${nocolor} - ${dnslookup_sorted[@]}"
done
