#!/bin/bash

#
#   Bulk domain output
#
#   `captaincore dns domain [<domain>...]`
#
#   Example output:
#   website1.com	Registrar: Tucows Reseller: Hover.com
#   website2.com	Registrar: Tucows Reseller: Hover.com
#

lightblue='\033[0;34m'
nocolor='\033[0m'

for var in "$@"; do
	whois=`whois $var`
	registrar=`echo "$whois" | grep "Registrar:" | tr -d '\r' | xargs`
	reseller=`echo "$whois" | grep "Reseller:"| tr -d '\r' | xargs`
	result="${registrar} ${reseller}"
	echo -e "${lightblue}${var}${nocolor} - ${result}"
done
