#!/usr/bin/env bash

#
#   Bulk email lookup
#
#   captaincore dns email [<domain>...]
#
#   Example output:
#   website1.com	Registrar: Tucows Reseller: Hover.com
#   website2.com	Registrar: Tucows Reseller: Hover.com
#

lightblue='\033[0;34m'
nocolor='\033[0m'

for var in "$@"; do
	dnslookup=`dig $var MX +short`
	dnslookup_sorted=(`echo $dnslookup | sort -n`)
	echo -e "${lightblue}${var}${nocolor} - ${dnslookup_sorted[@]}"
done
