#! /usr/bin/env php
<?php
##
##		Output array of domains from the logins
##
## 		Pass arguments from command line like this
##		captaincore get domains
##

parse_str(implode('&', array_slice($argv, 1)), $_GET);

if ($_GET && $_GET['file']) {
	$file = $_GET['file'];
} else {
	$file =  $_SERVER["HOME"] . "/Scripts/logins";
}

if (file_exists($file)) {
$file = file_get_contents($file);
	// Matches the format: installname)\n\n\t   See: http://regexr.com/3de13
	$pattern = '/domain=(.+)/';
	preg_match_all($pattern, $file, $matches);

	// print_r($matches);

	$space_separated = implode(" ", $matches[1]);

	echo $space_separated;
}
