#!/bin/bash

##
##		Grabs the Quicksave git commit status log
##
## 		Pass arguments from command line like this
##		captaincore get quicksave_changes <site> <git_hash>
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}/lib/arguments

website=$1
git_hash=$2


if [ $# -gt 0 ]
then

	quicksave_commit_status() {

		domain=`captaincore site get $website --field=domain`

		## Return error if domain not found
		if [[ "$domain" == "" ]]; then
			echo "Can't locate website for site $website"
			return 1
		fi

		cd $path/Quicksaves/$domain/
		git_show=`git show $git_hash --name-status --format=`
		echo "$git_show"

	}
	quicksave_commit_status

fi
