#!/bin/bash

##
##		Grabs the Quicksave git commit status log
##
## 		Pass arguments from command line like this
##		captaincore get quicksave_file_diff <site> <git_hash_current> <git_hash_previous> <file>
##
##		Example
##		captaincore get quicksave_file_diff anchorhost 4c43c16ae40f384e93573133282bb86a46d040fd a5ee8924e334debaba06de6f365a40caffa8586c versions/plugins.json
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

website=$1
git_hash=$2
git_hash_compare=$3
file=$4

# Loop through arguments and separate regular arguments from flags (--flag)
for var in "$@"
do
	# If starts with "--" then assign it to a flag array
    if [[ $var == --* ]]
    then
    	count=1+${#flags[*]}
    	flags[$count]=$var
    # Else assign to an arguments array
    else
    	count=1+${#arguments[*]}
    	arguments[$count]=$var
    fi
done

# Loop through flags and assign to variable. A flag "--email=austin@anchor.host" becomes $email
for i in "${!flags[@]}"
do

	# replace "-" with "_" and remove leading "--"
	flag_name=`echo ${flags[$i]} | tr - _`
	flag_name=`echo $flag_name | cut -c 3-`

	# detected flag contains data
	if [[ $flag_name == *"="* ]]; then
	  flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
	  flag_name=`echo $flag_name | perl -n -e '/(.+)?=.+/&& print $1'` # extract name
	  declare "$flag_name"="$flag_value" # assigns to $flag_flagname
	else
	  # assigns to $flag_flagname boolen
	  declare "$flag_name"=true
	fi

done

if [ $# -gt 0 ]
then

	quicksave_file_diff() {

		domain=`captaincore site get $website --field=domain`

		## Return error if domain not found
		if [[ "$domain" == "" ]]; then
			echo "Can't locate website for site $website"
			return 1
		fi

		cd ~/Quicksaves/$domain/
		git_diff=`git diff $git_hash $git_hash_compare -- $file`
		echo "$git_diff"

	}
	quicksave_file_diff

fi
