#!/bin/bash

##
##		Grabs the Quicksave git commit status log
##
## 		Pass arguments from command line like this
##		captaincore get quicksave_status <site> <git_hash>
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}/lib/arguments

site=$1
git_hash=$2

if [ $# -gt 0 ]; then

	quicksave_status() {

		eval $(captaincore site get $site --bash)

		## Return error if domain not found
		if [[ "$domain" == "" ]]; then
			echo "Can't locate website for site $site"
			return 1
		fi

		cd $path/${site}_${site_id}/quicksave/
		git_status=`git show $git_hash --shortstat --format=`
		echo "$git_status"

	}
	quicksave_status

fi
