#!/bin/bash

#
#   One time script to migrate from using $path/$site to $path/${site}_${site_id} for folders
#
#   `captaincore utils migrate-prep-for-staging`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

run_command() {
  if [ $# -gt 0 ]; then

    echo "Processing $# sites"
    INDEX=1
    for website in "$@"; do

      # Load site configs
      eval $(captaincore site get $website --bash)

      echo "Processing $site (${INDEX}/$#)"

      # Site found
      if ! [ -z "$domain" ]; then

        # Only move if destination does not exists
        if [ ! -d "$path/${site}_${site_id}/" ]; then
          mv $path/$site/ $path/${site}_${site_id}/
        fi

        # Only move if destination does not exists
        if [ ! -d "$path/${site}-staging_${site_id}/" ]; then
          mv $path/${site}-staging/ $path/${site}-staging_${site_id}/
        fi

      fi

      ### Clear out variables
      domain=''
      site=''
      username=''
      password=''
      address=''
      protocol=''
      port=''
      homedir=''
      remoteserver=''
      s3bucket=''
      s3path=''
      subsite=''

      let INDEX=${INDEX}+1
    done

  fi
}

# See if any sites are specified
if [ ${#arguments[*]} -gt 0 ]; then
  # Run on specific sites
  run_command ${arguments[*]}
else
  # Run on all sites
  run_command ${websites[@]}
fi
