#!/bin/bash

##
##      Download and store WP Engine snapshot on Dropbox
##
##      Pass arguments from command line like this
##      captaincore utils store_snapshot <url|file>
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
echo ${root_path}config

wpdownloadzip=$1
if [ -e $wpdownloadzip ]; then
	echo "Found local file $wpdownloadzip"
	rclone move $wpdownloadzip $rclone_archive -v
else
	wpdownloadzipfilename=`echo $wpdownloadzip | perl -n -e '/.+\/+(.+\.zip)/&& print $1'`
	wget -O $wpdownloadzipfilename $wpdownloadzip
	rclone move $wpdownloadzipfilename $rclone_archive -v
fi
