#!/bin/bash

##
##      Download and store WP Engine snapshot on Dropbox
##
##      Pass arguments from command line like this
##      captaincore manage store_snapshot
##

# Load configuration
source ~/Scripts/config

wpdownloadzip=$1
wpdownloadzipfilename=`echo $wpdownloadzip | perl -n -e '/\/(site.+.zip)/&& print $1'`
wget $wpdownloadzip
$path_rclone/rclone move $wpdownloadzipfilename Anchor-Dropbox:Backup/Archive/ -v
