#!/bin/zsh

##
##      Download and store WP Engine snapshot on Dropbox
##
##      Pass arguments from command line like this
##      captaincore utils store_snapshot <url|file>
##

# Load configuration
# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

wpdownloadzip=$1
if [ -f $wpdownloadzip ]; then
	echo "Found local file $wpdownloadzip"
	rclone move $wpdownloadzip Anchor-Dropbox:Backup/Archive/ -v
else
	wpdownloadzipfilename=`echo $wpdownloadzip | perl -n -e '/.+\/+(.+\.zip)/&& print $1'`
	wget -O $wpdownloadzipfilename $wpdownloadzip
	rclone move $wpdownloadzipfilename Anchor-Dropbox:Backup/Archive/ -v
fi
