#!/bin/bash

##
##      Download and store WP Engine snapshot on Dropbox
##
##      Pass arguments from command line like this
##      captaincore utils store_snapshot
##

# Load configuration
# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

wpdownloadzip=$1
wpdownloadzipfilename=`echo $wpdownloadzip | perl -n -e '/\/(site.+.zip)/&& print $1'`
wget $wpdownloadzip
rclone move $wpdownloadzipfilename Anchor-Dropbox:Backup/Archive/ -v
