#!/usr/bin/env bash

#
#   Fetches list of snapshots for a site from a backup repo
#
#   `captaincore site backup list <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

  INDEX=1
  for site in "$@"; do

   # Extract environment
    if [[ "$site" == *"-staging"* ]]; then
      environment=staging
    fi

    if [[ "$site" == *"-production"* ]]; then
      environment=production
    fi

    if [[ "$site" != *"-"* ]]; then
      environment=production
    fi

    # Load site configs
    while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

    backup_list="$path/${site}_${site_id}/${environment}/backups/list.json"
    if [ ! -f "$backup_list" ]; then
      captaincore site backup list-generate $site-$environment --captain_id=$captain_id
    fi
    cat "$backup_list"

  done

}

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi

# Runs on targeted sites
if [ ${#targets[*]} -gt 0 ]; then
  run_command $(captaincore site list ${targets[*]/targets=/@} --captain_id=$captain_id)
fi

# Error if no sites specifed
if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use a target @all, @production or @staging."
fi