#!/usr/bin/env bash

#
#   Apply SSL using domain with www
#

domain=$(wp option get home)
domain=${domain/http:\/\/www./}             # removes http://www.
domain=${domain/https:\/\/www./}            # removes https://www.
domain=${domain/http:\/\//}                 # removes https://
domain=${domain/https:\/\//}                # removes http://
domain=$( echo $domain | awk '{$1=$1};1' )  # Trims whitespace

echo "Search and replace http://$domain to https://www.$domain"
wp search-replace http://$domain https://www.$domain --all-tables --skip-plugins --skip-themes --report-changed-only
echo "Search and replace http://www.$domain to https://www.$domain"
wp search-replace http://www.$domain https://www.$domain --all-tables --skip-plugins --skip-themes --report-changed-only
wp cache flush
