#!/bin/bash

#
#   Import database
#

database_file=$@
wp db reset --yes
wp db import $database_file
siteurl=`wp option get siteurl`
siteurlhttp=${siteurl/https:/http:}
wp search-replace $siteurl $siteurlhttp --all-tables
