#!/usr/bin/env bash

#
#   Deploy Fathom
#
#   `deploy-fathom --tracker=<tracker-domain> --id=<site-id> --branding_author=<captaincore_branding_author> --branding_author_uri=<captaincore_branding_author_uri> --branding_slug=<captaincore_branding_slug>`
#

# Loop through arguments and separate regular arguments from flags
for arg in "$@"; do

  # Add to arguments array. (Does not starts with "--")
  if [[ $arg != --* ]]; then
    count=1+${#arguments[*]}
    arguments[$count]=$arg
    continue
  fi

  # Remove leading "--"
  flag_name=$( echo $arg | cut -c 3- )

  # Add to flags array
  count=1+${#flags[*]}
  flags[$count]=$arg

  # Process flags without data (Assign to variable)
  if [[ $arg != *"="* ]]; then
    flag_name=${flag_name//-/_}
    declare "$flag_name"=true
  fi

  # Process flags with data (Assign to variable)
  if [[ $arg == *"="* ]]; then
    flag_value=$( echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1' ) # extract value
    flag_name=$( echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1' ) # extract name
    flag_name=${flag_name/-/_}

    # Remove first and last quote if found
    flag_value="${flag_value%\"}"
    flag_value="${flag_value#\"}"

    declare "$flag_name"="$flag_value"
    continue
  fi

done

fathom_arguments=$( echo $fathom_arguments | base64 --decode )
while read -r line; do
    declare "$line"
done <<< "$fathom_arguments"

read -r -d '' php_code << heredoc
\$ids = '$id';
\$ids = json_decode(\$ids);
if( is_array(\$ids) ) { 
  echo count( \$ids ); 
}
heredoc

tracker_count=$( php -r "$php_code" )

read -r -d '' php_code << heredoc
\$ids = '$id';
\$ids = json_decode(\$ids);
echo \$ids[0]->code;
heredoc

if [[ "$tracker_count" -eq "1" ]]; then 
  id=$( php -r "$php_code" )
fi

if [[ "$tracker_count" -eq "1" ]] || [[ "$tracker_count" == "" ]]; then

# Generate must-use plugin
read -r -d '' build_mu_plugin << heredoc
<?php

/**
 * Plugin Name: $branding_author Stats
 * Description: Fathom Analytics tracking snippet for ${branding_author}'s bundled Fathom instance.
 * Version: 1.0
 * Author: $branding_author
 * Author URI: $branding_author_uri
 * Text Domain: ${branding_slug}-stats
 */

function ${branding_slug}_fathom_print_js_snippet() { ?>
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
(function(f, a, t, h, o, m){
	a[h]=a[h]||function(){
		(a[h].q=a[h].q||[]).push(arguments)
	};
	o=f.createElement('script'),
	m=f.getElementsByTagName('script')[0];
	o.async=1; o.src=t; o.id='fathom-script';
	m.parentNode.insertBefore(o,m)
})(document, window, '//$tracker/tracker.js', 'fathom');
fathom('set', 'siteId', '$id');
fathom('trackPageview');
</script>
<!-- / Fathom -->
<?php

}

add_action( 'wp_head', '${branding_slug}_fathom_print_js_snippet', 50 );
heredoc

else

read -r -d '' php_code << heredoc
\$ids = '$id';
\$ids = json_decode(\$ids);
echo '\$fathom_site_ids = array(';
echo "\n";
foreach (\$ids as \$id) { 
  echo '     "'.\$id->domain .'" => "'.\$id->code .'",';
  echo "\n";
}
echo "  );";
heredoc

fathom_site_ids_code=$( php -r "$php_code" )

# Generate must-use plugin
read -r -d '' build_mu_plugin << heredoc
<?php

/**
 * Plugin Name: $branding_author Stats
 * Description: Fathom Analytics tracking snippet for ${branding_author}'s bundled Fathom instance.
 * Version: 1.0
 * Author: $branding_author
 * Author URI: $branding_author_uri
 * Text Domain: ${branding_slug}-stats
 */

function ${branding_slug}_fathom_print_js_snippet() { 

  // Only run if multisite is active
  if (function_exists('get_blog_details')) {

  \$current_site = get_blog_details();

  $fathom_site_ids_code

  if ( array_key_exists( \$current_site->domain, \$fathom_site_ids ) ) {

                \$fathom_site_id = \$fathom_site_ids[\$current_site->domain];
  
  ?>
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
(function(f, a, t, h, o, m){
	a[h]=a[h]||function(){
		(a[h].q=a[h].q||[]).push(arguments)
	};
	o=f.createElement('script'),
	m=f.getElementsByTagName('script')[0];
	o.async=1; o.src=t; o.id='fathom-script';
	m.parentNode.insertBefore(o,m)
})(document, window, '//$tracker/tracker.js', 'fathom');
fathom('set', 'siteId', '<?php echo \$fathom_site_id; ?>');
fathom('trackPageview');
</script>
<!-- / Fathom -->
<?php

  }
  }
}

add_action( 'wp_head', '${branding_slug}_fathom_print_js_snippet', 50 );
heredoc

fi

echo "Generating 'wp-content/mu-plugins/${branding_slug}-stats.php'"
echo "$build_mu_plugin" > wp-content/mu-plugins/${branding_slug}-stats.php
