#!/bin/bash

#
#   Fetches site data
#
#   Returns: line 1: plugin data, line 2: theme data,
#   line 3: core version, line 4: home url, line 5: user data
#


plugins=$(wp plugin list --format=json --skip-themes --skip-plugins --skip-packages --fields=name,title,status,version)
themes=$(wp theme list --format=json --skip-themes --skip-plugins --skip-packages --fields=name,title,status,version)
core=$(wp core version --skip-themes --skip-plugins --skip-packages)
home_url=$(wp option get home --skip-themes --skip-plugins --skip-packages)
users=$(wp user list --format=json)

# Assume WP-CLI output may contain whitespaces and remove.
echo -e "${plugins}" | tr -d '[:space:]'
echo ""
echo -e "${themes}" | tr -d '[:space:]'
echo ""
echo -e "${core}" | tr -d '[:space:]'
echo ""
echo -e "${home_url}" | tr -d '[:space:]'
echo ""
echo -e "${users}" | tr -d '[:space:]'
