#!/bin/bash

#
#   Launches site - updates url from dev to live, enable search engine and clears cache
#
#   `launch --domain=<domain>`
#

COLOR_RED="\033[31m"
COLOR_NORMAL="\033[39m"

# Loop through arguments and separate regular arguments from flags (--flag)
for var in "$@"; do
  # If starts with "--" then assign it to a flag array
  if [[ $var == --* ]]; then
    count=1+${#flags[*]}
    flags[$count]=$var
    # Else assign to an arguments array
  else
    count=1+${#arguments[*]}
    arguments[$count]=$var
  fi
done

# Loop through flags and assign to variable. A flag "--email=austin@anchor.host" becomes $email
for i in "${!flags[@]}"; do

  # replace "-" with "_" and remove leading "--"
  flag_name=`echo ${flags[$i]} | cut -c 3-`

  # detected flag contains data
  if [[ $flag_name == *"="* ]]; then
    flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
    flag_name=`echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1'` # extract name
    flag_name=${flag_name/-/_}
    declare "$flag_name"="$flag_value" # assigns to $flag_flagname
  else
    # assigns to $flag_flagname boolen
    declare "$flag_name"=true
  fi

done

run_command() {

	if [[ $site == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify --site=<site>."
    exit 1
  fi

  if [[ $domain == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify --domain=<domain>."
    exit 1
  fi

  wp search-replace "${site}.wpengine.com" "$domain" --all-tables --skip-plugins --skip-themes --report-changed-only
  wp search-replace "${site}.kinsta.com" "$domain" --all-tables --skip-plugins --skip-themes --report-changed-only
  wp option update blog_public 1
  wp cache flush

}

run_command
