#!/usr/bin/env bash

#
#   Launches site - updates url from dev to live, enable search engine and clears cache
#
#   `launch --domain=<domain>`
#

COLOR_RED="\033[31m"
COLOR_NORMAL="\033[39m"

# Loop through arguments and separate regular arguments from flags
for arg in "$@"; do

  # Add to arguments array. (Does not starts with "--")
  if [[ $arg != --* ]]; then
    count=1+${#arguments[*]}
    arguments[$count]=$arg
    continue
  fi

  # Remove leading "--"
  flag_name=$( echo $arg | cut -c 3- )

  # Add to flags array
  count=1+${#flags[*]}
  flags[$count]=$arg

  # Process flags without data (Assign to variable)
  if [[ $arg != *"="* ]]; then
    flag_name=${flag_name//-/_}
    declare "$flag_name"=true
  fi

  # Process flags with data (Assign to variable)
  if [[ $arg == *"="* ]]; then
    flag_value=$( echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1' ) # extract value
    flag_name=$( echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1' ) # extract name
    flag_name=${flag_name/-/_}

    # Remove first and last quote if found
    flag_value="${flag_value%\"}"
    flag_value="${flag_value#\"}"

    declare "$flag_name"="$flag_value"
    continue
  fi

done

run_command() {

	if [[ $site == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify --site=<site>."
    exit 1
  fi

  if [[ $domain == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify --domain=<domain>."
    exit 1
  fi

  echo "Search and replace ${site}.wpengine.com to $domain"
  wp search-replace "${site}.wpengine.com" "$domain" --all-tables --skip-plugins --skip-themes --report-changed-only
  echo "Search and replace ${site}.kinsta.cloud to $domain"
  wp search-replace "${site}.kinsta.cloud" "$domain" --all-tables --skip-plugins --skip-themes --report-changed-only
  echo "Search and replace ${site}.kinsta.com to $domain"
  wp search-replace "${site}.kinsta.com" "$domain" --all-tables --skip-plugins --skip-themes --report-changed-only
  wp option update blog_public 1
  wp cache flush

}

run_command
