#!/bin/bash

#
#   Update themes and plugins
#
#   `update`
#
#   [--<field>=<value>]
#   Extra arguments to pass to `[wp theme update](https://developer.wordpress.org/cli/commands/theme/update/)` and `[wp plugin update]( https://developer.wordpress.org/cli/commands/plugin/update/)`.
#

# Loop through arguments and separate regular arguments from flags (--flag)
for var in "$@"; do

  # If starts with "--" then assign it to a flag array
  if [[ $var == --* ]]; then
    count=1+${#flags[*]}
    flags[$count]=$var
    # Else assign to an arguments array
  else
    count=1+${#arguments[*]}
    arguments[$count]=$var
  fi

done

# Loop through flags and assign to variable. A flag "--email=my-email@my-site.com" becomes $email
for i in "${!flags[@]}"; do

  # replace "-" with "_" and remove leading "--"
  flag_name=`echo ${flags[$i]} | cut -c 3-`

  # detected flag contains data
  if [[ $flag_name == *"="* ]]; then
    flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
    flag_name=`echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1'` # extract name
    flag_name=${flag_name/-/_}
    declare "$flag_name"="$flag_value" # assigns to $flag_flagname
		if [[ "$flag_name" == "script" ]] || [[ "$flag_name" == "exclude_plugins" ]] || [[ "$flag_name" == "exclude_themes" ]] || [[ "$flag_name" == "site" ]]; then
			unset flags[$i]
		fi
  else
    # assigns to $flag_flagname boolen
    flag_name=${flag_name//-/_}
    declare "$flag_name"=true
  fi

done

# Store current path
homedir=$(pwd)

run_command() {

  # Find private folder
  if [ ! -d "_wpeprivate" ] && [ ! -d "../private" ]; then
    echo "Can't find private folder '/_wpeprivate' or '../private'. Updates skipped.";
    return 1
  fi
  if [ -d "_wpeprivate" ]; then
    private=${homedir}/_wpeprivate
  fi
  if [ -d "../private" ]; then
    cd ../private
    private=$(pwd)
    cd $homedir
  fi

  echo "<?php define( 'WP_ADMIN', true ); ?>" > $private/require_wp_admin.php

  if [[ $exclude_themes == "" ]]; then
  	wp theme update ${flags[@]} --require="$private/require_wp_admin.php"
  else
  	wp theme update ${flags[@]} --require="$private/require_wp_admin.php" --exclude=$exclude_themes
  fi
  echo " "
  if [[ $exclude_plugins == "" ]]; then
  	wp plugin update ${flags[@]} --require="$private/require_wp_admin.php"
  else
  	wp plugin update ${flags[@]} --require="$private/require_wp_admin.php" --exclude=$exclude_plugins
  fi

}
run_command
