#!/bin/bash

#
#   Update themes and plugins
#
#   `update`
#
#   [--<field>=<value>]
#   Extra arguments to pass to `[wp theme update](https://developer.wordpress.org/cli/commands/theme/update/)` and `[wp plugin update]( https://developer.wordpress.org/cli/commands/plugin/update/)`.
#

# Loop through arguments and separate regular arguments from flags (--flag)
for var in "$@"; do

  # If starts with "--" then assign it to a flag array
  if [[ $var == --* ]]; then
    count=1+${#flags[*]}
    flags[$count]=$var
    # Else assign to an arguments array
  else
    count=1+${#arguments[*]}
    arguments[$count]=$var
  fi

done

# Loop through flags and assign to variable. A flag "--email=my-email@my-site.com" becomes $email
for i in "${!flags[@]}"; do

  # replace "-" with "_" and remove leading "--"
  flag_name=`echo ${flags[$i]} | cut -c 3-`

  # detected flag contains data
  if [[ $flag_name == *"="* ]]; then
    flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
    flag_name=`echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1'` # extract name
    flag_name=${flag_name/-/_}
    declare "$flag_name"="$flag_value" # assigns to $flag_flagname
		if [[ "$flag_name" == "script" ]] || [[ "$flag_name" == "exclude_plugins" ]] || [[ "$flag_name" == "exclude_themes" ]] || [[ "$flag_name" == "site" ]]; then
			unset flags[$i]
		fi
  else
    # assigns to $flag_flagname boolen
    flag_name=${flag_name//-/_}
    declare "$flag_name"=true
  fi

done

if [[ $exclude_themes == "" ]]; then
	wp theme update ${flags[@]}
else
	wp theme update ${flags[@]} --exclude=$exclude_themes
fi
echo " "
if [[ $exclude_plugins == "" ]]; then
	wp plugin update ${flags[@]}
else
	wp plugin update ${flags[@]} --exclude=$exclude_plugins
fi
