#!/usr/bin/env bash

#
#   Update themes and plugins
#
#   `update`
#
#   [--<field>=<value>]
#   Extra arguments to pass to `[wp theme update](https://developer.wordpress.org/cli/commands/theme/update/)` and `[wp plugin update]( https://developer.wordpress.org/cli/commands/plugin/update/)`.
#

# Loop through arguments and separate regular arguments from flags
for arg in "$@"; do

  # Add to arguments array. (Does not starts with "--")
  if [[ $arg != --* ]]; then
    count=1+${#arguments[*]}
    arguments[$count]=$arg
    continue
  fi

  # Remove leading "--"
  flag_name=$( echo $arg | cut -c 3- )

  # Add to flags array
  count=1+${#flags[*]}
  if [[ "$arg" != "--script"* ]] && [[ "$arg" != *"--exclude_plugins"* ]] && [[ "$arg" != "--exclude_themes"* ]] && [[ "$arg" != "--site"* ]] && [[ "$arg" != "--provider"* ]] && [[ "$arg" != "--captain_id"* ]]; then
    # Remove first and last quote if found
    arg_for_flag="${arg%\"}"
    arg_for_flag="${arg_for_flag/=\"/=}"
    flags[$count]=$arg_for_flag
  fi

  # Process flags without data (Assign to variable)
  if [[ $arg != *"="* ]]; then
    flag_name=${flag_name//-/_}
    declare "$flag_name"=true
  fi

  # Process flags with data (Assign to variable)
  if [[ $arg == *"="* ]]; then
    flag_value=$( echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1' ) # extract value
    flag_name=$( echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1' ) # extract name
    flag_name=${flag_name/-/_}

    # Remove first and last quote if found
    flag_value="${flag_value%\"}"
    flag_value="${flag_value#\"}"

    declare "$flag_name"="$flag_value"
    continue
  fi

done

# Store current path
home_directory=$(pwd)

run_command() {

  # Find private folder
  if [ ! -d "_wpeprivate" ] && [ ! -d "../private" ]; then
    echo "Can't find private folder '/_wpeprivate' or '../private'. Updates skipped.";
    return 1
  fi
  if [ -d "_wpeprivate" ]; then
    private=${home_directory}/_wpeprivate
  fi
  if [ -d "../private" ]; then
    cd ../private
    private=$(pwd)
    cd $home_directory
  fi

  echo "<?php define( 'WP_ADMIN', true ); ?>" > $private/require-wp-admin.php

  if [[ $exclude_themes == "" ]]; then
  	wp theme update ${flags[@]} --require="$private/require-wp-admin.php"
  else
  	wp theme update ${flags[@]} --require="$private/require-wp-admin.php" --exclude=$exclude_themes
  fi
  echo " "
  if [[ $exclude_plugins == "" ]]; then
    wp plugin update ${flags[@]} --require="$private/require-wp-admin.php"
  else
  	wp plugin update ${flags[@]} --require="$private/require-wp-admin.php" --exclude=$exclude_plugins
  fi
  # Handle WooCommerce database updates if installed
  if $( wp plugin is-installed woocommerce ); then 
    silent=$( wp wc update 2>&1 )
    # Handle WooCommerce database updates on multisite if installed
    if $( wp core is-installed --network ); then 
      for site_id in $( wp site list --field=blog_id ); do
        site_url=$( wp site list --field=url --blog_id=${site_id} )
        if $( wp plugin is-active woocommerce --url=$site_url ); then
            silent=$( wp wc update --url=${site_url} 2>&1 )
        fi
      done
    fi
  fi
  silent=$( wp cache flush )
  if [[ $provider == "kinsta" ]]; then
    silent=$( wp kinsta cache purge )
  fi

}
run_command
