#!/usr/bin/env bash

#
#   Fetch running processes
#
#   `captaincore running listen`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

for log in $( find ${path}/ -maxdepth 1 -name 'process-*-progress.log' ); do
    php ${root_path}lib/local-scripts/process-track.php $log "json"
done

inotifywait -q -m -e create -e close_write -e close -e delete -e delete_self ${path} | while read -r dir event file; do
    if [[ "$event" == "DELETE" ]]; then
        process_id=${filename//process-/}
    fi
    if [[ "$event" == "CLOSE_WRITE"* ]]; then
        php ${root_path}lib/local-scripts/process-track.php ${dir}$file "json"
    fi
done
