#!/bin/bash

##
##      Removes custom deactivate mu-plugin to batch of installs
##
##      Pass arguments from command line like this
##      captaincore manage activate install1 install2
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

# Paths
plugin="anchorhost_deactivated"

activate () {
for (( i = 1; i <= $#; i++ )); do
    var="$i"
    website=${!var}

    ### Load FTP credentials
		eval $(captaincore site get $website --bash)

    ### Credentials found, start the backup
    if ! [ -z "$domain" ]; then

      ### remove deactivation plugin
      rclone delete sftp-$website:$homedir/wp-content/mu-plugins/$plugin.php
      echo "activated $domain"

    fi

    ### Clear out variables
    domain=''
    username=''
    password=''
    address=''
    protocol=''
    port=''

done

}

### See if any specific sites are selected
if [ $# -gt 0 ]; then
    ## Run selected installs
    activate $*
fi
