#!/bin/bash

##
##      Deploys custom deactivate mu-plugin to batch of installs
##
##      Pass arguments from command line like this
##      captaincore manage deactivate install1 install2
##


# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

# Paths
local_path="$path/anchor.host/deploy"
plugin="anchorhost_deactivated"

deactivate () {
for (( i = 1; i <= $#; i++ )); do
    var="$i"
    website=${!var}

    ### Load FTP credentials
		source $root_path/logins

    ### Credentials found, start the backup
    if ! [ -z "$domain" ]; then

      ### upload deactivation plugin to mu-plugins
      rclone copy $local_path/$plugin.php sftp-$website:$homedir/wp-content/mu-plugins/

      echo "deactivated $domain"

    fi

    ### Clear out variables
    domain=''
    username=''
    password=''
    ipAddress=''
    protocol=''
    port=''

done

}

### See if any specific sites are selected
if [ $# -gt 0 ]; then
    ## Run selected installs
    deactivate $*
fi
