#!/usr/bin/env bash

#
#   Initializes site
#
#   `captaincore site deploy-init <site>`
#
#   [--skip-remote]
#
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

  echo "Run init on $# sites"
  INDEX=1

  for website in "$@"; do

    # Extract environment
		if [[ "$website" == *"-staging"* ]]; then
			environment=staging
		else
			environment=production
		fi

    # Load site configs
    while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $website --bash --captain_id=$captain_id)"

    if [[ $domain == "" ]]; then
      echo "Error: $site missing domain."
      continue
    fi

    # Define Rclone site name
    rclone_site_name=${captain_id}-${site}-${environment}

    # Captures FTP errors in $ftp_output and file listing to log file
    ftp_output=$( { rclone lsd sftp-$rclone_site_name:$home_directory ; } 2>&1 )
    ftp_search_for_wordpress=$( echo "$ftp_output" | perl -wnE'say for /wp-admin/g' )

    # Handle FTP errors
    if [[ $ftp_search_for_wordpress != "wp-admin" ]]; then
      echo "Error: $site missing WordPress."
      continue
    fi

    # Append trailing slash if home_directory exist
    if [ "$home_directory" != "" ]; then
      home_directory="${home_directory}/"
    fi

    # Pull down wp-config.php and .htaccess
    rclone copy sftp-$rclone_site_name:${home_directory}wp-config.php $path/${site}_${site_id}/${environment}/backup/
    rclone copy sftp-$rclone_site_name:${home_directory}.htaccess $path/${site}_${site_id}/${environment}/backup/

    # load custom configs into wp-config.php and .htaccess
    captaincore site deploy-configs $site --captain_id=$captain_id
    sleep 1s

    # Push up modified wp-config.php and .htaccess
    rclone copy $path/${site}_${site_id}/${environment}/backup/wp-config.php sftp-$rclone_site_name:${home_directory}
    rclone copy $path/${site}_${site_id}/${environment}/backup/.htaccess sftp-$rclone_site_name:${home_directory}

    # Generate token
    token_key=$(captaincore site fetch-token $site --captain_id=$captain_id)

    if [[ "$captaincore_dev" == true ]]; then
      curl_argument="-k"
    fi

    # Assign token
    curl ${curl_argument} --request POST "$captaincore_api" --header "Content-Type: application/json" --data @- << EOF
{
	"command":"token",
	"site_id":"$site_id",
	"token_key":"$token_key",
	"token":"$token"
}
EOF

  if [[ $skip_remote != "true" ]]; then

    # Set permalink to 'Post name' format if not set
    captaincore ssh ${site} --script=rewrite-prep --captain_id=$captain_id

    # Deploy helper plugin
    captaincore ssh ${site} --script=deploy-helper --captain_id=$captain_id
    captaincore ssh ${site}-staging --script=deploy-helper --captain_id=$captain_id

  fi

    # Clear out variables
    domain=''
    username=''
    password=''
    address=''
    protocol=''
    port=''
    home_directory=''
    remoteserver=''

    let INDEX=${INDEX}+1
  done

}

if [ ${#arguments[*]} -gt 0 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi

# Runs on targeted sites
if [ ${#targets[*]} -gt 0 ]; then
  run_command $(captaincore site list ${targets[*]/targets=/@} --captain_id=$captain_id)
fi

# Error if no sites specifed
if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use a target @all, @production or @staging."
fi