#!/usr/bin/env bash

#
#   Fetch token for site
#
#   `captaincore site fetch-token <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

site=${arguments[1]}

# Extract environment
if [[ "$site" == *"-staging"* ]]; then
    environment=staging
else
    environment=production
fi

# Load site configs
while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

if [ -f $path/${site}_${site_id}/${environment}/backup/wp-config.php ]; then

    # Grabs AUTH_KEY line from wp-config.php
    auth_code=$(grep "'AUTH_KEY'" $path/${site}_${site_id}/${environment}/backup/wp-config.php | awk -F "'" '{print $4}')

    # PHP script to parse and base64
    read -r -d '' php_code << heredoc
\$auth_key = '$auth_code';
echo md5(\$auth_key);
heredoc

    php -r "$php_code"

fi