#!/usr/bin/env bash

#
#   Fetch token for site
#
#   `captaincore site fetch-token <site>`
#

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(php ${CAPTAINCORE_PATH}/lib/local-scripts/configs.php fetch)"

if [ ${#@} -ne 1 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."
  exit
fi

site=$1

# Extract environment
if [[ "$site" == *"-staging"* ]]; then
    environment=staging
else
    environment=production
fi

# Load site configs
while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain-id=$CAPTAIN_ID)"

if [ -f $path/${site}_${site_id}/${environment}/backup/wp-config.php ]; then

    # Grabs AUTH_KEY line from wp-config.php
    auth_code=$(grep "'AUTH_KEY'" $path/${site}_${site_id}/${environment}/backup/wp-config.php | awk -F "'" '{print $4}')

    # PHP script to parse and base64
    read -r -d '' php_code << heredoc
\$auth_key = '$auth_code';
echo md5(\$auth_key);
heredoc

    php -r "$php_code"

fi