#! /usr/bin/env php
<?php
#
#   Generates WP-CLI commands based on an API call to CaptainCore GUI containing list of users
#
#   captaincore site fetch-default-users <site>
#

if (isset($argv)) {
    parse_str(implode('&', array_slice($argv, 1)), $_GET);
}

$captain_id   = $_GET['--captain_id'];
$site         = $argv[1];
$site_details = json_decode( shell_exec( "captaincore site get $site --format=json --captain_id=$captain_id" ) );

// Loads CLI configs
$json = $_SERVER['HOME'] . '/.captaincore-cli/config.json';

if ( ! file_exists( $json ) ) {
	return;
}

$config_data = json_decode ( file_get_contents( $json ) );
$system = $config_data[0]->system;

foreach($config_data as $config) {
	if ( isset( $config->captain_id ) and $config->captain_id == $captain_id ) {
		$configuration = $config;
		break;
	}
}

$preloaded_users = array();

// Fetches from CLI configs
$captaincore_gui = $configuration->vars->captaincore_gui;
$token           = shell_exec( "captaincore site fetch-token $site --captain_id=$captain_id" );

$customers = explode(",", $site_details->preloadusers );

foreach ( $customers as $customer ) {

    $url = "$captaincore_gui/wp-json/wp/v2/captcore_customer/$customer/?token=$token";

    $curl = curl_init( $url );
    curl_setopt( $curl, CURLOPT_SSL_VERIFYHOST, 0 );
    curl_setopt( $curl, CURLOPT_SSL_VERIFYPEER, 0 );
    curl_setopt( $curl, CURLOPT_RETURNTRANSFER, 1);

    $response = curl_exec( $curl );
    $response = json_decode( $response, true );
    $users = $response["preloaded_users"];
    foreach ($users as $user) {
        $preloaded_users[] = (object) $user;
    }

}

// Output WP-CLI commands
foreach( $preloaded_users as $user ) {
    echo "wp user create {$user->username} {$user->email} --role={$user->role} --first_name={$user->first_name} --last_name={$user->last_name} --send-email\n";
}