#!/bin/bash

#
#   Gets details about a site.
#
#   `captaincore site get <site>`
#
#   [--field=<field>]
#   Returns specific field
#
#   [--bash]
#   Return in bash format
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}/lib/arguments

run_command() {

  site=$1
  cd ${root_path}data

  # Requires <site>
  if [[ "$site" == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one a site."
    return 1
  fi

  if [[ "$bash" == "true" ]]; then
    website_id=$(captaincore site get $site --field=ID)
    wp eval-file ${root_path}lib/php/site-get.php $website_id
    return 1
  fi

  if [[ "$field" == "" ]]; then
    declare -a rows
    wp post list --post_type=captcore_website --posts_per_page=1 --meta_key=site --meta_value="$site" --meta_compare="=" --fields="ID,site,address,username,password,protocol,port,site_staging,address_staging,username_staging,password_staging,protocol_staging,port_staging" --format=json | json
  elif [[ "$field" == "domain" ]]; then
    wp post list --post_type=captcore_website --posts_per_page=1 --meta_key=site --meta_value="$site" --meta_compare="=" --fields=post_title --format=json | json -a post_title
  else
    wp post list --post_type=captcore_website --posts_per_page=1 --meta_key=site --meta_value="$site" --meta_compare="=" --fields=$field --format=json | json -a $field
  fi

}
run_command ${arguments[*]}
