#!/bin/bash

##
##		Output array of installs from the logins
##
## 		Pass arguments from command line like this
##		captaincore site get <install> --field=domain [--bash]
##
##		Expected results
##		anchor.host
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}

# Loop through arguments and seperate regular arguments from flags (--flag)
for var in "$@"
do
	# If starts with "--" then assign it to a flag array
    if [[ $var == --* ]]
    then
    	count=1+${#flags[*]}
    	flags[$count]=$var
    # Else assign to an arguments array
    else
    	count=1+${#arguments[*]}
    	arguments[$count]=$var
    fi
done

# Loop through flags and assign to varible. A flag "--email=austin@anchor.host" becomes $email
for i in "${!flags[@]}"; do

	# replace "-" with "_" and remove leading "--"
	flag_name=`echo ${flags[$i]} | tr - _`
	flag_name=`echo $flag_name | cut -c 3-`

	# detected flag contains data
	if [[ $flag_name == *"="* ]]; then
	  flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
	  flag_name=`echo $flag_name | perl -n -e '/(.+)?=.+/&& print $1'` # extract name
	  declare "$flag_name"="$flag_value" # assigns to $flag_flagname
	else
	  # assigns to $flag_flagname boolen
	  declare "$flag_name"=true
	fi

done

cd $root_path/data

process_get() {
if [[ "$bash" == "true" ]]; then
	website_id=$(captaincore site get $1 --field=ID)
	wp eval-file ${root_path}lib/php/site-get.php $website_id
	return 1
fi

if [[ "$field" == "" ]]; then
	declare -a rows
	wp post list --post_type=captcore_website --posts_per_page=1 --meta_key=install --meta_value="$1" --meta_compare="=" --fields="ID,install,address,username,password,protocol,port,install_staging,address_staging,username_staging,password_staging,protocol_staging,port_staging" --format=json | json
elif [[ "$field" == "domain" ]]; then
	wp post list --post_type=captcore_website --posts_per_page=1 --meta_key=install --meta_value="$1" --meta_compare="=" --fields=post_title --format=json | json -a post_title
else
	wp post list --post_type=captcore_website --posts_per_page=1 --meta_key=install --meta_value="$1" --meta_compare="=" --fields=$field --format=json | json -a $field
fi
}
process_get $1
