#!/bin/bash

#
#   Gets details about a site.
#
#   `captaincore site get <site>`
#
#   [--field=<field>]
#   Returns specific field
#
#   [--bash]
#   Return in bash format
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}/lib/arguments

run_command() {

  site=$1
  cd ${root_path}data

  # Requires <site>
  if [[ "$site" == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one a site."
    return 1
  fi

  # Detect if provider passed into <site>
  if [[ "$site" == *"@"* ]]; then
    provider=$(echo $site | awk -F@ '{print $2}')
    site=$(echo $site | awk -F@ '{print $1}')
  fi

  if [[ "$bash" == "true" ]]; then
		# Output bash format
    wp eval-file ${root_path}lib/php/site-get.php site=$site provider=$provider format=bash field=$field
  elif [[ "$field" != "" ]]; then
		# Output raw format
		wp eval-file ${root_path}lib/php/site-get.php site=$site provider=$provider format=json field=$field
	else
		# Output json format
    wp eval-file ${root_path}lib/php/site-get.php site=$site provider=$provider format=json field=$field | json
  fi

}
run_command ${arguments[*]}
