#! /usr/bin/env php
<?php
##
##		Output array of installs from the logins
##
## 		Pass arguments from command line like this
##		captaincore site list [--all] [--staging] [--plugin=<plugin>] [--theme=<theme>]
##
##		TO DO
##		- switch backend from TXT files to local copy of WordPress.
##		- switch over to bash script
##
##		Usage would look something like this to check for websites with WooCommerce and return only the website install names in bash array
## 		websites=( $(wp post list --post_type=captcore_website --meta_key=plugins --meta_value='"name":"woocommerce"' --meta_compare="LIKE" --fields=install --format=json | json -a install) )
##
##		Create
##		wp post create --meta_input='{"install":"anchorhost1","address":"anchorhost1.wpengine.com"}' --post_title='anchorhost1.wpengine.com' --post_status=publish --post_type=captcore_website
##
##		List all
##		echo $(wp post list --post_type=captcore_website --fields=install | json -a install)
##

parse_str(implode('&', array_slice($argv, 1)), $_GET);

if ($_GET && $_GET['file']) {
	$file = $_GET['file'];
} else {
	$file = $_SERVER["HOME"] . "/.captaincore-cli/logins";
}

if (file_exists($file)) {
$file = file_get_contents($file);
	// Matches the format: installname)\n\n\t   See: http://regexr.com/3de13
	$pattern = '/(\w+)(?=\)\n\t\t)/';
	preg_match_all($pattern, $file, $matches);

	// print_r($matches);

	$space_separated = implode(" ", $matches[0]);

	echo $space_separated;
}
