#!/bin/bash

#
#   Lists sites
#
#   `captaincore site list`
#
#   [--all] [--staging] [--filter=<theme|plugin|core>] [--filter-name=<name>] [--filter-version=<version>] [--filter-status=<active|inactive|dropin|must-use>] [--field=<field>]
#


# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

# Remove leading "--" from flags
for i in "${!flags[@]}"; do
	flags[$i]=`echo ${flags[$i]} | cut -c 3-`
done

cd ${root_path}data

wp eval-file ${root_path}lib/php/site-list.php ${flags[@]}
