#!/usr/bin/env bash

#
#   Search for site name
#
#   <search>
#
#   [--field=<field>]
#   Output specified field. Defaults to site name.
#
#   [--search-field=<field>]
#   Expands search to addition field
#


# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

cd ${root_path}data

wp eval-file ${root_path}lib/local-scripts/site-search.php search=$1 field=$field search-field=$search_field captain_id=$captain_id
