#!/usr/bin/env bash

#
#   Flag site with SSH failure.
#
#   `captaincore site ssh-fail <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

  site=$1

  # Remove leading "--" from flags
  for i in "${!flags[@]}"; do
    flags[$i]=`echo ${flags[$i]} | cut -c 3-`
  done

  cd ${root_path}data

  # Extract environment
  if [[ "$website" == *"-staging"* ]]; then
    environment=staging
  else
    environment=production
  fi

  # Load site configs
  while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

  if [[ "$protocol" == "sftp" ]]; then
    echo "SSH failed $site"
    wp eval-file ../lib/local-scripts/site-ssh-failed.php site=$site environment=$environment ${flags[@]}
  fi

}
run_command ${arguments[*]}
