#!/usr/bin/env bash

#
#   Syncs site details to CaptainCore CLI.
#
#   `captaincore site sync <site_id>`
#
#    [--update-extras]
#    
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	site_id=$1

	# Remove leading "--" from flags
	for i in "${!flags[@]}"; do
		flags[$i]=`echo ${flags[$i]} | cut -c 3-`
	done

	cd ${root_path}data
	wp eval-file ../lib/local-scripts/site-sync.php site_id=$site_id ${flags[@]}

	if [ "$update_extras" ]; then

		# Generate rclone keys
		captaincore rclone-configs $site_id --captain_id=$captain_id

		# Prepare site
		captaincore prep $site_id --skip-deployment --captain_id=$captain_id

	fi

}

# See if any sites are specifed
if [ ${#arguments[*]} -eq 1 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi

# Error if no sites specifed
if [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."
fi