#!/bin/bash

#
#   Loads new site configurations into logins via command line
#
#   `captaincore site update <site> --id=<id> --domain=<domain> --username=<username> --password=<password> --address=<address> --protocol=<protocol> --port=<port> --staging_username=<staging_username> --staging_password=<staging_password> --staging_address=<staging_address> --staging_protocol=<staging_protocol> --staging_port=<staging_port> [--preloadusers=<preloadusers>] [--homedir=<homedir>] [--s3accesskey=<s3accesskey>] [--s3secretkey=<s3secretkey>] [--s3bucket=<s3bucket>] [--s3path=<s3path>]`
#
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

# Remove leading "--" from flags
for i in "${!flags[@]}"; do
	flags[$i]=`echo ${flags[$i]} | cut -c 3-`
done

cd ${root_path}data
wp eval-file ../lib/php/site-update.php site=$1 ${flags[@]}

# Load site configs
eval $(captaincore site get $1 --bash)

# Generate rclone keys
captaincore rclone-configs $site

# Prep site without deploying plugins or users (in background)
captaincore prep $site --skip-deployment
