#!/usr/bin/env bash

#
#   Updates field for a site in CaptainCore CLI.
#
#   `captaincore site update-field <site> <field> <value>`
#
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	# Remove leading "--" from flags
	for i in "${!flags[@]}"; do
		flags[$i]=`echo ${flags[$i]} | cut -c 3-`
	done

    # Load site configs
	while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $1 --bash --captain_id=$captain_id)"

	cd ${root_path}data
	wp eval-file ../lib/local-scripts/site-update-field.php site=$1 $2 $3 site_id=$site_id ${flags[@]}

}

# See if any sites are specifed
if [ ${#arguments[*]} -eq 3 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi

# Error if no sites specifed
if [ ${#arguments[*]} -ne 3 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."
fi