#!/bin/bash

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

website=$1

### Load FTP credentials
eval $(captaincore site get $website --bash)

### Credentials found, start the backup
if ! [ -z "$domain" ]
then

	# Remove if already found
	rclone config delete sftp-$website
	rclone config delete sftp-$website-staging

	echo "$(date +'%Y-%m-%d %H:%M') Generating rclone configs for $website"

	password=$(captaincore site get $website --field=password)
	password_staging=$(captaincore site get $website --field=password_staging)

	# Add new WordPress site to Rclone
	rclone_pass=$(rclone obscure $password)
	rclone config create sftp-$website sftp host $address user $username port $port pass $rclone_pass

	if [[ "$password_staging" != "" ]]; then
		rclone_pass_staging=$(rclone obscure $password_staging)
		rclone config create sftp-$website-staging sftp host $address_staging user $username_staging port $port_staging pass $rclone_pass_staging
	fi

fi
