#!/bin/bash

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

website=$1

### Load FTP credentials
source $root_path/logins

### Credentials found, start the backup
if ! [ -z "$domain" ]
then

	# Remove if already found
	rclone config delete sftp-$website
	rclone config delete sftp-$website-staging

	echo "$(date +'%Y-%m-%d %H:%M') Generating rclone configs for $website"
	# Add new WordPress site to Rclone
	rclone_pass=$(rclone obscure $password)
	rclone_pass_staging=$(rclone obscure $staging_password)
	rclone config create sftp-$website sftp host $ipAddress user $username port $port pass $rclone_pass
	rclone config create sftp-$website-staging sftp host $staging_ipAddress user $staging_username port $staging_port pass $rclone_pass_staging

fi
