#!/usr/bin/env bash

#
#   Syncs account details to CaptainCore CLI.
#
#   `captaincore account sync <account_id>`
#    
#

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(php ${CAPTAINCORE_PATH}/lib/local-scripts/configs.php fetch)"

account_id=$1

run_command() {

	cd ${CAPTAINCORE_PATH}/data
	wp eval-file ../lib/local-scripts/account-sync.php account_id=$account_id

}

run_command