#!/bin/bash

#
#   Removes custom deactivate mu-plugin to batch of sites
#
#   `captaincore activate [<site>...]`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config

run_command() {
for (( i = 1; i <= $#; i++ )); do
    var="$i"
    site=${!var}

    # Load site configs
		eval $(captaincore site get $site --bash)

    # Site found, start the backup
    if ! [ -z "$domain" ]; then

			if [[ "$homedir" != "" ]]; then
				homedir="${homedir}/"
			fi

      ### remove deactivation plugin
      rclone delete sftp-$site:${homedir}wp-content/mu-plugins/captaincore_deactivated.php
      echo "activated $domain"

    fi

    ### Clear out variables
    domain=''
    username=''
    password=''
    address=''
    protocol=''
    port=''

done

}

### See if any specific sites are selected
if [ $# -gt 0 ]; then
    ## Run selected site(s)
    run_command $*
fi
