#!/usr/bin/env bash

#
#   Removes custom deactivate mu-plugin to batch of sites
#
#   `captaincore activate [<site>...]`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

  for website in "${arguments[*]}"; do

  	# Extract environment
		if [[ "$website" == *"-staging"* ]]; then
			environment=staging
		else
			environment=production
		fi

    # Load site configs
    while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $website --bash --captain_id=$captain_id)"

    if [ -z "$domain" ]; then
      echo "Domain not found"
      continue
    fi

    # Define Rclone site name
		rclone_site_name=${captain_id}-${site}-${environment}

    if [[ "$home_directory" != "" ]]; then
      home_directory="${home_directory}/"
    fi

    # Remove deactivation plugin
    rclone delete sftp-$rclone_site_name:${home_directory}wp-content/mu-plugins/captaincore_deactivated.php
    echo "activated $domain"

  done

}

# See if any specific sites are selected
if [ $# -gt 0 ]; then
  # Run selected site(s)
  run_command $*
fi
