#!/usr/bin/env bash

#
#   Backups one or more sites.
#
#   `captaincore backup`
#
#   [<site>...]
#   One or more sites.
#
#   [@<target>]
#   Target groups of sites like @all @production or @staging.
#
#   [--parallel=<number>]
#   Number of sites to backup at same time
#
#   [--skip-remote]
#   Skips saving to Restic backup repo
#
#   [--skip-db]
#   Skips database backup
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	sites=$@
  count=( $sites )

  echo ${#count[@]} > ${root_path}data/process-${process_id}-progress.log

	# Assign default parallel if needed
	if [[ $parallel == "" ]]; then
		parallel=3
	fi
	echo $sites | xargs -P $parallel -n 1 captaincore backup-runner "${flags[@]}"

}

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi

# Runs on targeted sites
if [ ${#targets[*]} -gt 0 ]; then
  run_command $(captaincore site list ${targets[*]/targets=/@} --captain_id=$captain_id)
fi

# Error if no sites specifed
if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use a target @all, @production or @staging."
fi