#!/usr/bin/env bash

#
#   Copy staging to production (Kinsta only)
#
#   `captaincore copy-staging-to-production <site> --email=<email>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

run_command() {

  echo "Deploying $# production sites"
  INDEX=1
  for website in "$@"; do

    # Load site configs
    eval $(captaincore site get $website --bash)

    # Vars found, proceed
    if [ -z "$domain" ]; then
      echo "Domain not found"
      return
    fi

    if [ "$homedir" != "" ]; then
      homedir="${homedir}/"
    fi

    # Unique timestamp
    timestamp=$(date +%s)

    # Grab core version
    core_version=$( captaincore ssh $site-staging --command="wp core version" )

    captaincore ssh $site-staging --command="wp db export --skip-plugins --skip-themes --add-drop-table - > wp-content/mysql.sql; zip -r wp-content_$timestamp.zip wp-content/ --exclude=wp-content/uploads/\* --exclude=wp-content/updraft/\*"

    staging_home_url=$( captaincore ssh $site-staging --command="wp option get home --skip-plugins --skip-themes" )

    # Download staging snapshot to production site and import database
    captaincore ssh $site --script=migrate --update-urls --url="${staging_home_url}/wp-content_$timestamp.zip"

    # Remove from production_to_staging
    captaincore ssh $site-staging --command="rm -f wp-content_$timestamp.zip"

    # Install matching core version
    captaincore ssh $site --command="wp core update --version=$core_version"

    # Sync uploads folders
    rclone sync sftp-${site}-staging:${homedir}wp-content/uploads/ sftp-${site}:${homedir}wp-content/uploads/ -v

    # Post completion to CaptainCore API
    if [[ $captaincore_dev == true ]]; then
      curl_argument="-k"
    fi

    curl ${curl_argument} --request POST "$captaincore_api" --header "Content-Type: application/json" --data @- << EOF
{
"command":"staging-to-production",
"site_id":"$site_id",
"email":"$email",
"token":"$token"
}
EOF

    # Clear out variables
    domain=''
    username=''
    password=''
    address=''
    protocol=''
    port=''
    username_staging=''
    password_staging=''
    address_staging=''
    protocol_staging=''
    port_staging=''
    preloadusers=''
    homedir=''
    remoteserver=''
    s3bucket=''
    s3path=''
    subsite=''

    let INDEX=${INDEX}+1
  done

}

# See if any specific sites are selected
if [ ${#arguments[*]} -gt 0 ]; then
  # Deploy staging site to production
  run_command ${arguments[*]}
fi
