#!/usr/bin/env bash

#
#   Downloads old databases from Rclone remote
#
#   `captaincore db-restore <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

site=$1

db_revisions=$(rclone --include "/mysql*.sql" lsjson --no-modtime --b2-versions $rclone_backup/${site}_${site_id}/backup/wp-content/ | json -a Name)

PS3="Select database file: "
 select database in $db_revisions; do
	 if [ -n "$database" ]; then
			 database_file=${database}
	 fi
	 break
 done

echo "Selected ${database}"

rclone -q --b2-versions copyto $rclone_backup/${site}_${site_id}/backup/wp-content/${database} $path_tmp/restore-db/$site-${database}
# captaincore upload $site $path_tmp/restore-db/$domain-${database} --public
# captaincore ssh $site --script=db-import $domain-${database}
