#!/usr/bin/env bash

#
#   Deploys custom deactivate mu-plugin on one or more sites.
#
#   `captaincore deactivate`
#
#    [<site>...]
#    One or more sites to deactivate.
#
#    [--name=<business-name>]
#    Custom name to display on deactivate page.
#
#    [--link=<business-link>]
#    Custom link to display on deactivate page.
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

# Unique timestamp
timestamp=$(date +%s)

# Must use WordPress deactivate plugin
cat <<EOF > ~/Tmp/captaincore_deactivated_${timestamp}.php
<?php

function captaincore_template_redirect() { ?><html>
  <head>
	<meta charset="utf-8">
	<title>Website Deactivated</title>

	<!-- Compiled and minified CSS -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

	<!-- Compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

	<style>
		@import url('https://fonts.googleapis.com/css?family=Roboto');
		body {
			text-align: center;
			margin: 10% auto;
			padding: 0%;
			font-family: 'Roboto', sans-serif;
			overflow: hidden;
			display: block;
			max-width: 450px;
			background: #eeeeee;
		}
		p {
		  margin-top: 3%;
		  line-height: 1.4em;
		  display: block;
		}
		img {
		  margin-top: 1%;
		}
		a {
			color:#27c3f3;
		}
	</style>
  </head>
  <body>
		<div class="row">
	<div class="col s12">
	  <div class="card">
		<div class="card-content">
					<span class="card-title">Website Deactivated</span>
						<p>This website is no longer active.</p>
		</div>
				<div class="card-content grey lighten-4">
					<p>Site owners contact <a href="${link}">${name}</a></p>
				</div>
	  </div>
	</div>
  </div>


	</body>
</html>

<?php

  die();

}
add_action( 'template_redirect', 'captaincore_template_redirect' );
EOF

run_command() {

	for website in "${arguments[*]}"; do

		# Extract environment
		if [[ "$website" == *"-staging"* ]]; then
			environment=staging
		else
			environment=production
		fi

    	# Load site configs
		while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $website --bash --captain_id=$captain_id)"

		if [[ $domain == "" ]]; then
			echo "Domain not found"
			continue
		fi

		# Define Rclone site name
		rclone_site_name=${captain_id}-${site}-${environment}

		if [[ "$home_directory" != "" ]]; then
			home_directory="${home_directory}/"
		fi

		# Upload deactivation plugin to mu-plugins
		rclone copyto ~/Tmp/captaincore_deactivated_${timestamp}.php sftp-${rclone_site_name}:${home_directory}${wp_content}/mu-plugins/captaincore_deactivated.php

		echo "deactivated $domain"

	done

}

# See if any specific sites are selected
if [ $# -gt 0 ]; then
    # Run on selected site(s)
    run_command ${arguments[*]}
fi
