#!/usr/bin/env bash

#
#   Syncs default settings to CaptainCore CLI.
#
#   `captaincore default-sync`
#

run_command() {
  cd ${CAPTAINCORE_PATH}/data
  wp eval-file ../lib/local-scripts/default-sync.php ${flags[@]}
}

if [ ${#arguments[*]} -eq 0 ]; then
  run_command ${arguments[*]}
fi