#!/usr/bin/env bash

#
#   Downloads file from site
#
#   `captaincore download <site> <file>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

site=$1

# Load site configs
while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

# Site found
if ! [ -z "$domain" ]; then

  ## If website on Kinsta then connect SSH using their format
  if [[ "$provider" == "kinsta" ]]; then

		if [ -n "$2" ]; then
			scp -o StrictHostKeyChecking=no -P $port $username@$address:public/$2 $2
		else
			echo 'Missing argument. Ex: captaincore download sitename1 logo.png'
		fi

  else ## If not Kinsta then try connecting using WP Engine's format
		echo "Download..."
		if [ -n "$2" ]; then
		  scp -o StrictHostKeyChecking=no -P 22 $1@$1.ssh.wpengine.net:sites/$1/$2 $2
		else
		  echo 'Missing argument. Ex: captaincore download sitename1 logo.png'
		fi

  fi

else ## not recognized so attempt WP Engine's format

	if [ -n "$2" ]; then
	  scp -o StrictHostKeyChecking=no -P 22 $1@$1.ssh.wpengine.net:sites/$1/$2 $2
	else
	  echo 'Missing argument. Ex: captaincore download sitename1 logo.png'
	fi

fi
