#!/usr/bin/env bash

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config

# Make new local WordPress site
cd ~/Sites
mkdir $1
cd $1
valet secure
wp core download
wp config create --dbname=$1 --dbuser=root --dbpass=$local_wp_db_pw
wp db create
wp core install --url=https://$1.test --admin_user=$captaincore_admin_user --admin_email=$captaincore_admin_email --title=$1
wp option update timezone_string America/New_York
open $(wp option get home)/wp-login.php
