#!/usr/bin/env bash

#
#   Login to WordPress using links
#
#   Credit to [One Time Login](https://wordpress.org/plugins/one-time-login/)
#
#   `captaincore login <site> <login>`
#
#   [--open]
#   Opens in browser
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

site=$1
login=$2

run_command() {

	# Load site configs
	eval $(captaincore site get $site --bash)

	if [[ $site == "" ]]; then
		echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."
	fi

	if [[ $login == "" ]]; then
		echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a login."
	fi

	# Append trailing slash if home_directory exist
	if [ "$home_directory" != "" ]; then
		home_directory="${home_directory}/"
	fi

	# Fetch login
	magic_link=$(captaincore ssh $site --command="wp plugin install one-time-login --activate; wp user one-time-login '$login'")
	magic_link=${magic_link##*$'\n'} # Returns last line if multiple are returned
	magic_link=${magic_link//http:/https:} # Changes to https url

	if [[ "$open" == "true" ]]; then
		open ${magic_link}
	else
		echo -n "${magic_link}"
	fi

}

run_command
