#!/usr/bin/env bash

#
#   Generates Manifest
#
#   `captaincore generate-manifest`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

cd ${root_path}data

wp eval-file ${root_path}lib/local-scripts/manifest-generate.php captain_id=$captain_id --user=1