#!/bin/bash

#
#   Monitor check on a site.
#
#   `captaincore monitor-check <site>`
#

run_command () {

  # Load site configs
  eval $(captaincore site get $1 --bash)

  # Bail if home url not defined
  if [[ "$home_url" == "" ]]; then
    echo "Skipping $website, WordPress home url not found"
    return 1
  fi

  # Run the health check. Return http_code and body.
  response=$(curl -A "$user_agent" --write-out %{http_code} --max-time 30 --silent $home_url)

  # Pull out http code
  http_code=${response:${#response}-3}

  # Pull out body
  body=${response:0:${#response}-3}

  # valid body contains </html>
  html_end_tag=$(echo $body | perl -wnE'say for /<\/html>/g')

  # check if </html> found
  if [[ $html_end_tag == "</html>" ]]; then
    html_end_tag_check="true"
  else
    html_end_tag_check="false"
  fi

  # Build json for output
  read -r -d '' json_output << EOM
{
"http_code":"$http_code",
"url":"$home_url",
"site_id":"$site_id",
"html_valid":"$html_end_tag_check"
}
EOM

	echo $json_output

}

run_command $1
