#!/usr/bin/env bash

#
#   Monitor check one or more sites.
#
#   `captaincore monitor`
#
#   [<site>...]
#   One or more sites to check.
#
#   [@<target>]
#   Target groups of sites like @all @production or @staging.
#
#   [--urls="<url1> <url2> <url3>"]
#
#   [--retry=<number-of-retries>]
#   Number of retries for failures. Defaults to 3.
#
#   [--parallel=<number-of-checks>]
#   Number of monitor checks to run at same time. Defaults to 15.
#
#   [--page=<page-url>]
#   Check a specific page. Example `--page=/wp-admin/`. Defaults to home page.
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

  urls_to_check=()

  # Assign default retry
  if [[ $retry == "" ]]; then
    retry=3
  fi

  # Assign default parallel
  if [[ $parallel == "" ]]; then
    parallel=15
  fi

  # See if any sites are specifed
  if [ ${#arguments[*]} -gt 0 ]; then
    # Runs on specific sites
    for site in ${arguments[*]}; do
      url=$( captaincore site get $site --field=home_url --captain_id=$captain_id )
      urls_to_check+=( ${url}${page},${site} )
    done
    urls_to_check=${urls_to_check[@]}
  fi

  if [[ ${#urls} != 0 ]]; then
    urls_to_check=${urls}
  fi

  if [ ${#targets[*]} -gt 0 ]; then
    # Runs on all sites
    urls=$( captaincore site list ${targets[*]/targets=/@} --field=home_url --captain_id=$captain_id )
    for url in ${urls[*]}; do
      urls_to_check+=( ${url}${page},${site} )
    done
    urls_to_check=${urls_to_check[@]}
  fi

  orignal_urls_to_check=$urls_to_check

  # Error if no sites specifed
  if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -eq 0 ] && [[ ${#urls} == 0 ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use @production."
    return 1
  fi

  # Generate random auth
  auth=''; for count in {0..6}; do auth+=$(printf "%x" $(($RANDOM%16)) ); done;

  # Begin time tracking
  overalltimebegin=$(date +"%s")
  backup_date=$(date +'%Y-%m-%d')
  backup_time=$(date +'%H-%M')

  # Define log file format
  log_file=$logs/${backup_date}_${backup_time}_$auth.txt

  # Define monitor.json location
  monitor_file="$path/monitor.json"

  echo "logging to $log_file"

  cd ${root_path}data

  for attempt in $(seq 1 $retry); do

    # Wait before retrying failures
    sleep 10s

    # Run checks in parallel. Collect the results in log file.
    ( echo $urls_to_check | xargs -P $parallel -n 1 captaincore monitor-check ) 2>&1 | tee $log_file

    # Have local PHP handle error count
    error_count=$(php ${root_path}lib/local-scripts/monitor.php check $log_file $monitor_file)

    # If no errors then skip the rest of the attempts.
    if [[ $error_count == "0" ]]; then
      break
    fi

    # Skip last attempt
    if [[ $attempt != $retry ]]; then 

      echo "Attempt #${attempt} found $error_count errors. Checking those URLs again.";

      # Fetch urls with errors for another another check
      urls_to_check=$(php ${root_path}lib/local-scripts/monitor.php process $log_file $monitor_file)

      # Empty space for formating
      echo "" >> $log_file
      
    else

      echo "Attempt #${attempt} found $error_count errors."

    fi

  done

  # Build emails
  email_content=$(php ${root_path}lib/local-scripts/monitor.php generate $log_file $monitor_file "$orignal_urls_to_check")

  if [[ $email_content != "" ]]; then

    echo "Sending Email"
    echo $email_content

    # output "Response code $response for $address" per each item in array
    echo $email_content | mutt -e 'set content_type=text/html' -s "Monitor: $error_count errors" -- $captaincore_admin_email

  fi

}
run_command
