#!/usr/bin/env bash

#
#   Monitor check on a single valid HTTP url.
#
#   `captaincore monitor-check <site>`
#

# Vars
user_agent="captaincore/1.0 (CaptainCore Health Check by CaptainCore.io)"
url=$1

run_command() {

  # Run the health check. Return http_code and body.
  response=$(curl --user-agent "$user_agent" --write-out %{http_code} --max-time 30 --silent $url)

  # Pull out http code
  http_code=${response:${#response}-3}

  # Pull out body
  body=${response:0:${#response}-3}

  # valid body contains </html>
  html_end_tag=$(echo -e "$body" | perl -wnE'say for /<\/html>/g')

  # check if </html> found
  if [[ $html_end_tag == "</html>" ]]; then
    html_end_tag_check="true"
  else
    html_end_tag_check="false"
  fi

  # Build json for output
  read -r -d '' json_output << EOM
{
"http_code":"$http_code",
"url":"$url",
"html_valid":"$html_end_tag_check"
}
EOM

	echo $json_output

}

run_command $1
