#!/usr/bin/env bash

#
#   Extract subsite from a Multisite network
#
#   `captaincore multisite-extract-subsite <site-source> <site-destination> <subsite-id>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

# Prompts for multisite site name, single site name and subsite id.
site_name_source=$1
site_name_destination=$2
subsite_id=$3

run_command() {

  if [[ $site_name_source == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify <site-source>."
    return 1
  fi

  if [[ $site_name_destination == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify <site-destination>."
    return 1
  fi

  if [[ $subsite_id == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify <subsite-id>."
    return 1
  fi

  homedir_source=$( captaincore site get $site_name_source --field=homedir)
  homedir_destination=$( captaincore site get $site_name_destination --field=homedir)

  # Append trailing slash if homedir exist
  if [ "$homedir_source" != "" ]; then
    homedir_source="${homedir_source}/"
  fi

  # Append trailing slash if homedir exist
  if [ "$homedir_destination" != "" ]; then
    homedir_destination="${homedir_destination}/"
  fi

  # Check and sync legacy multisite upload files
  folder_check=$( { rclone lsd sftp-${site_name_source}:wp-content/blogs.dir/${subsite_id}/files/ ; } 2>&1 )
  if [[ $folder_check != *"directory not found"* ]]; then
    echo "Found legacy subsite uploads (wp-content/blogs.dir/${subsite_id}/files/). Transferring..."
    rclone sync sftp-${site_name_source}:${homedir_source}wp-content/blogs.dir/${subsite_id}/files/ sftp-${site_name_destination}:${homedir_destination}wp-content/uploads/ -v
  fi

  # Check and sync modern multisite upload files
  folder_check=$( { rclone lsd sftp-${site_name_source}:wp-content/uploads/sites/${subsite_id}/ ; } 2>&1 )
  if [[ $folder_check != *"directory not found"* ]]; then
    echo "Found subsite uploads (wp-content/uploads/sites/${subsite_id}/). Transferring..."
    rclone sync sftp-${site_name_source}:${homedir_source}wp-content/uploads/sites/${subsite_id}/ sftp-${site_name_destination}:${homedir_destination}wp-content/uploads/ -v
  fi

  subsite_url=$( captaincore ssh $site_name_source --command="wp site list --site__in=${subsite_id} --field=url" )
  active_themes=( $( captaincore ssh $site_name_source --command="wp theme list --url=${subsite_url} --status=parent --field=name; wp theme list --url=${subsite_url} --status=active --field=name" ) )
  active_plugins=( $( captaincore ssh $site_name_source --command="wp plugin list --status=active-network --field=name; wp plugin list --url=${subsite_url} --status=active --field=name" ) )

  for theme in ${active_themes[@]}; do
    echo "Copying theme ${theme}"
    rclone sync sftp-${site_name_source}:${homedir_source}wp-content/themes/${theme} sftp-${site_name_destination}:${homedir_destination}wp-content/themes/${theme} -v
  done

  for plugin in ${active_plugins[@]}; do
    echo "Copying plugin ${plugin}"
    rclone sync sftp-${site_name_source}:${homedir_source}wp-content/plugins/${plugin} sftp-${site_name_destination}:${homedir_destination}wp-content/plugins/${plugin} -v
  done

  return 1

}
run_command
