#!/usr/bin/env bash

#
#   Generates plugin zips on a single site.
#
#   `captaincore plugins-zip <site> <plugin>...`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

site=$1
plugins=${arguments[@]/$site}

captaincore ssh $site --script=plugins-zip --plugins="$plugins" --captain_id=$captain_id
