#!/usr/bin/env bash

#
#   Generates plugin zips on a single site.
#
#   `captaincore plugins-zip <site> <plugin>...`
#

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(captaincore config fetch --captain-id=$CAPTAIN_ID)"

if [ ${#@} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Requires a <site>"
  exit
fi

site=$1
count=( $@ )
plugins=${@:2:${#@}}

# Join plugins with commas so they survive SSH command string interpolation
plugins_csv=$(echo "$plugins" | tr ' ' ',')

captaincore ssh $site --script=plugins-zip -- --plugins="$plugins_csv"
