#! /usr/bin/env php
<?php
//
// Generates list of plugins (separated by space) based on an API call to CaptainCore's Wordpress Site (captaincore_gui) containing list of plugins to preload
//
// Pass arguments from command line like this
// captaincore plugins-get --customers=1294,1245 --token=random
//
if ( isset( $argv ) ) {
	parse_str( implode( '&', array_slice( $argv, 1 ) ), $_GET );
}

$token     = $_GET['--token'];
$customers = explode( ',', $_GET['--customers'] );

$preloaded_users = array();

// Loads CLI configs
$file = $_SERVER['HOME'] . '/.captaincore-cli/config';
if ( file_exists( $file ) ) {

	$file = file_get_contents( $file );
	// Matches config keys and values
	$pattern = '/(.+)=\"(.+)\"/';
	preg_match_all( $pattern, $file, $matches );

}

// Fetches from CLI configs
$captaincore_gui_key = array_search( 'captaincore_gui', $matches[1] );
$captaincore_gui    = $matches[2][ $captaincore_gui_key ];

// Loads WordPress
include $_SERVER['HOME'] . '/data/wp-settings.php';

foreach ( $customers as $customer ) {

	$curl = curl_init( "$captaincore_gui/wp-json/wp/v2/captcore_customer/$customer/?token=$token" );
	curl_setopt( $curl, CURLOPT_RETURNTRANSFER, 1 );
	$response             = curl_exec( $curl );
	$json_results_website = json_decode( $response, true );
	if ( isset( $json_results_website['preloaded_plugins'] ) ) {

		$preloaded_plugins = [];

		$plugins = $json_results_website['preloaded_plugins'];

		foreach ( $plugins as $plugin ) {
			$preloaded_plugins[] = $plugin;
		}
	}
}

$output = '';
if ( isset( $preloaded_plugins ) ) {
	foreach ( $preloaded_plugins as $preloaded_plugin ) {
		$plugin  = $preloaded_plugin['plugin'];
		$output .= $plugin . ' ';
	}
}

echo trim( $output );
