#!/usr/bin/env bash

#
#   Preps new site configurations into logins via command line
#
#   `captaincore prep <site>`
#
#   [--skip-deployment]
#   Skip users and plugin deployment
#

root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

site=$1

# Load site details
eval $(captaincore site get $site --bash)

# Deploy SSH keys
captaincore deploy keys ${site}@${provider}

# load custom configs into wp-config.php and .htaccess, setups up token
captaincore deploy init ${site}@${provider}
echo "load custom configs into wp-config.php and .htaccess"
echo "Setting up token"

if [[ $skip_deployment != true ]]; then

  ## loads users
  captaincore deploy users ${site}@${provider}
  echo "Preload Users"

  ## install plugins
  captaincore deploy plugins ${site}@${provider}
  echo "Preload Plugins"

  ## run initial backup
  captaincore backup ${site}@${provider}
  echo "Running Initial Backup"

fi

captaincore sync-data ${site}@${provider}
