#!/usr/bin/env bash

#
#   Preps new site configurations into logins via command line
#
#   `captaincore prep <site>`
#
#   [--skip-deployment]
#   Skip users and plugin deployment
#

root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

site=$1

# Load site details
while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

# Deploy SSH keys
captaincore site deploy-keys ${site} --captain_id=$captain_id
captaincore site deploy-keys ${site}-staging --captain_id=$captain_id

# load custom configs into wp-config.php and .htaccess, setups up token
captaincore site deploy-init $site --captain_id=$captain_id
echo "load custom configs into wp-config.php and .htaccess"
echo "Setting up token"

# Generate new Fathom code if needed
if [[ $captaincore_tracker != "" ]] && [[ $fathom == "" ]]; then

  # Generate new Fathom tracking code, if needed
  captaincore site stats-generate ${site}-production --captain_id=$captain_id
  captaincore site stats-generate ${site}-staging --captain_id=$captain_id

fi

if [[ $skip_deployment != true ]]; then

  # loads users
  captaincore site deploy-users $site --captain_id=$captain_id
  echo "Deploy Default Users"

  # install plugins
  captaincore site deploy-plugins $site --captain_id=$captain_id
  echo "Deploy Default Plugins"

  # Deploy  Recipes
  captaincore site deploy-recipes $site --captain_id=$captain_id
  echo "Deploy Default Recipes"

  # Deploy Settings
  captaincore site deploy-settings $site --captain_id=$captain_id
  echo "Deploy Default Settings (admin_user and timezone_string)"

fi

captaincore sync-data $site --captain_id=$captain_id
captaincore sync-data ${site}-staging --captain_id=$captain_id

# Update configs
captaincore configs update-websites --captain_id=$captain_id