#!/usr/bin/env bash

#
#   Preps new site configurations into logins via command line
#
#   `captaincore prep <site>`
#
#   [--skip-deployment]
#   Skip users and plugin deployment
#

root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

site=$1

if [[ "$captain_id" == "" ]]; then
  captain_id=1
fi

# Load site details
while read site_configs; do declare "$site_configs"; done <<< $(captaincore site get $site --bash --captain_id=$captain_id)

# Deploy SSH keys
captaincore deploy keys $site

# load custom configs into wp-config.php and .htaccess, setups up token
captaincore deploy init $site
echo "load custom configs into wp-config.php and .htaccess"
echo "Setting up token"

if [[ $skip_deployment != true ]]; then

  ## loads users
  captaincore deploy users $site
  echo "Preload Users"

  ## install plugins
  captaincore deploy plugins $site
  echo "Preload Plugins"

  ## run initial backup
  captaincore backup $site
  echo "Running Initial Backup"

fi

captaincore sync-data $site
captaincore sync-data ${site}-staging
