#!/usr/bin/env bash

#
#   Grabs Quicksave git commit status log
#
#   `captaincore quicksave-view-changes <site> --hash=<git_hash>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	for website in "$@"; do

		# Extract environment
		if [[ "$website" == *"-staging"* ]]; then
			environment=staging
		else
			environment=production
		fi


		while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $website --bash --captain_id=$captain_id)"

		# Return error if domain not found
		if [[ "$domain" == "" ]]; then
			echo "Can't locate website for site $site"
			return 1
		fi

		cd $path/${site}_${site_id}/${environment}/quicksave/
		git_show=`git show $hash --name-status --format=`
		echo "$git_show"

	done

}

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ]; then
  # Runs on specific sites
  run_command ${arguments[*]}
fi

# Error if no sites specifed
if [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use --all."
fi
