#!/bin/bash

#
#   Grabs file diff between Quicksaves
#
#   `captaincore quicksave-file-diff <site> <git_hash_current> <git_hash_previous> <file>`
#
#   Example: captaincore quicksave-file-diff sitename 4c43c16ae40f384e93573133282bb86a46d040fd a5ee8924e334debaba06de6f365a40caffa8586c versions/plugins.json
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

site=$1
git_hash=$2
git_hash_compare=$3
file=$4

if [ $# -gt 0 ]; then

  run_command() {

		eval $(captaincore site get $site --bash)

    # Return error if domain not found
    if [[ "$domain" == "" ]]; then
      echo "Can't locate website for site $site"
      return 1
    fi

    cd $path/${site}_${site_id}/quicksave/
    git_diff=`git diff $git_hash $git_hash_compare -- $file`
    echo "$git_diff"

  }
  run_command

fi
