#!/usr/bin/env bash

#
#   Grabs file diff between Quicksaves
#
#   `captaincore quicksave-file-diff <site> --hash=<git_hash> --file=<file>`
#
#   [--html]
#   HTML converted output
#
#   Example: captaincore quicksave-file-diff sitename 4c43c16ae40f384e93573133282bb86a46d040fd versions/plugins.json
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	for website in "$@"; do

		# Extract environment
		if [[ "$website" == *"-staging"* ]]; then
			environment=staging
		else
			environment=production
		fi

		while read site_configs; do declare "$site_configs"; done <<< "$(captaincore site get $website --bash --captain_id=$captain_id)"

		# Return error if domain not found
		if [[ "$domain" == "" ]] || [[ "$site" == "" ]] || [[ "$provider" == "" ]]; then
		  echo "Can't locate website for site $site"
		  return 1
		fi

		cd $path/${site}_${site_id}/${environment}/quicksave/

		# capture all git commit into array
		git_commits=($( git log --pretty=format:"%H" ))

		for i in ${!git_commits[@]}; do
			if [[ "${git_commits[$i]}" == "$hash" ]]; then
				current_index=$i
			fi
		done

		git_hash_previous=${git_commits[ $(( $current_index + 1 )) ]}
		git_diff=$( git diff $git_hash_previous $hash -- $file )
		if [[ $html == "true" ]]; then

			read -r -d '' php_code << heredoc
<?php
error_reporting(0);
\$git_diff = <<<PHPHEREDOC
$git_diff
PHPHEREDOC;

echo htmlentities( \$git_diff );
heredoc

			echo -n "$php_code" > $path_tmp/${captain_id}-${hash}.php
			php $path_tmp/${captain_id}-${hash}.php

		else
			echo "$git_diff"
		fi

	done

}

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi

# Runs on targeted sites
if [ ${#targets[*]} -gt 0 ]; then
  run_command $(captaincore site list ${targets[*]/targets=/@} --captain_id=$captain_id)
fi

# Error if no sites specifed
if [ ${#targets[*]} -eq 0 ] && [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use a target @all, @production or @staging."
fi