#!/bin/bash

#
#   Grabs file diff between Quicksaves
#
#   `captaincore quicksave-file-diff <site> <git_hash_current> <file>`
#
#   Example: captaincore quicksave-file-diff sitename 4c43c16ae40f384e93573133282bb86a46d040fd versions/plugins.json
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

site=$1
git_hash=$2
git_hash_compare=$3
file=$4

if [ $# -gt 0 ]; then

  run_command() {

		eval $(captaincore site get $site --bash)

    # Return error if domain not found
    if [[ "$domain" == "" ]]; then
      echo "Can't locate website for site $site"
      return 1
    fi

    cd $path/${site}_${site_id}/quicksave/

		# capture all git commit into array
		git_commits=($(git log --pretty=format:"%H"))

		for i in ${!git_commits[@]}; do
			if [[ "${git_commits[$i]}" == "$git_hash" ]]; then
				current_index=$i
			fi
		done

		git_hash_previous=${git_commits[ $(( $current_index + 1 )) ]}
    git_diff=`git diff $git_hash $git_hash_previous -- $file`
    echo "$git_diff"

  }
  run_command

fi
