#!/bin/bash

#
#   Generates rclone configs based on site credentials
#
#   `captaincore site rclone-configs <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config

site=$1

# Load site vars
eval $(captaincore site get $site --bash)

# Credentials found, proceed
if ! [ -z "$domain" ]; then

	# Remove if already found
	rclone config delete sftp-$site
	rclone config delete sftp-$site-staging

	echo "$(date +'%Y-%m-%d %H:%M') Generating rclone configs for $site"

	password=$(captaincore site get $site --field=password)
	password_staging=$(captaincore site get $site --field=password_staging)

	# Add new WordPress site to Rclone
	rclone_pass=$(rclone obscure $password)
	rclone config create sftp-$site $protocol host $address user $username port $port pass $rclone_pass

	if [[ "$password_staging" != "" ]]; then
		rclone_pass_staging=$(rclone obscure $password_staging)
		rclone config create sftp-$site-staging $protocol_staging host $address_staging user $username_staging port $port_staging pass $rclone_pass_staging
	fi

fi
