#!/usr/bin/env bash

#
#   Rollback theme, plugin or file from a Quicksave on a site.
#
#   `captaincore rollback <site> <commit>`
#
#   [--plugin=<plugin>]
#
#   [--theme=<theme>]
#
#   [--file=<file>]
#
#   [--all]
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

  site=$1
  commit=$2

  # Requires <site> and <commit>
  if [[ $site == "" ]] || [[ $commit == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site and a commit."
    return 1
  fi

  # Requires <site> and <commit>
  if [[ $plugin == "" ]] && [[ $theme == "" ]] && [[ $all == "" ]] && [[ $file == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a plugin, theme, file or --all."
    return 1
  fi

  # Extract environment
  if [[ "$site" == *"-staging"* ]]; then
    environment=staging
  else
    environment=production
  fi

  # Load site info
  while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

  # Define Rclone site name
  rclone_site_name=${captain_id}-${site}-${environment}

  if [[ "$plugin" != "" ]]; then

    echo "Rolling back plugin $plugin"
    cd $path/${site}_${site_id}/${environment}/quicksave/
    mkdir -p ~/Tmp/restore/$commit/
    git archive --format=zip $commit:plugins/$plugin/ > ~/Tmp/restore/$commit/$plugin.zip
    captaincore upload ${site}-${environment} ~/Tmp/restore/$commit/$plugin.zip --public --captain_id=$captain_id
    captaincore ssh ${site}-${environment} --command="rm -rf ${wp_content}/plugins/$plugin/; unzip $plugin.zip -d ${wp_content}/plugins/$plugin/; rm $plugin.zip" --captain_id=$captain_id
    rm -rf ~/Tmp/restore/$commit/

  fi

  if [[ "$theme" != "" ]]; then

    echo "Rolling back theme $theme"
    cd $path/${site}_${site_id}/${environment}/quicksave/
    mkdir -p ~/Tmp/restore/$commit/
    git archive --format=zip $commit:themes/$theme/ > ~/Tmp/restore/$commit/$theme.zip
    captaincore upload ${site}-${environment} ~/Tmp/restore/$commit/$theme.zip --public --captain_id=$captain_id
    captaincore ssh ${site}-${environment} --command="rm -rf ${wp_content}/themes/$theme/; unzip $theme.zip -d ${wp_content}/themes/$theme/; rm $theme.zip" --captain_id=$captain_id
    rm -rf ~/Tmp/restore/$commit/

  fi

	if [[ "$file" != "" ]]; then

		file_name=${file##*/}
		file_path=${file//$file_name/}
		echo "Rolling back file '$file'"
		cd $path/${site}_${site_id}/${environment}/quicksave/
		mkdir -p ~/Tmp/restore/$commit/$file_path
		git show $commit:$file > ~/Tmp/restore/$commit/$file
		if [[ "$home_directory" != "" ]]; then
			home_directory="${home_directory}/"
		fi
		rclone copyto ~/Tmp/restore/$commit/$file sftp-$rclone_site_name:${home_directory}${wp_content}/$file
		rm -rf ~/Tmp/restore/$commit/

	fi

  if [[ "$all" == "true" ]]; then

    echo "Rolling back entire quicksave"
    cd $path/${site}_${site_id}/${environment}/quicksave/
    mkdir -p ~/Tmp/restore/$commit/
    git archive --format=zip $commit: > ~/Tmp/restore/$commit/quicksave_${commit}_all.zip
    captaincore upload ${site}-${environment} ~/Tmp/restore/$commit/quicksave_${commit}_all.zip --public --captain_id=$captain_id
    echo '<?php $upgrading = time(); ?>' | captaincore ssh ${site}-${environment} --command="cat > .maintenance; rm -rf ${wp_content}/themes/; unzip -q -o quicksave_${commit}_all.zip 'themes/*' -d ${wp_content}/; rm -rf ${wp_content}/plugins/; unzip -q -o quicksave_${commit}_all.zip 'plugins/*' -d ${wp_content}/; rm -rf ${wp_content}/mu-plugins/; unzip -q -o quicksave_${commit}_all.zip 'mu-plugins/*' -d ${wp_content}/; rm .maintenance" --captain_id=$captain_id
    rm -rf ~/Tmp/restore/$commit/

  fi

}
run_command ${arguments[*]}
