#!/bin/bash

##
##		Rollback (theme/plugin) from a quicksave
##
## 		Pass arguments from command line like this
##		captaincore rollback <site> <commit> [--plugin=<plugin>] [--theme=<theme>] [--all-plugins] [--all-themes] [--all]
##
website=$1
commit=$2

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

### Load FTP credentials
eval $(captaincore site get $website --bash)

# if [ "$homedir" == "" ]; then
# 		homedir="/"
# fi

# Loop through arguments and separate regular arguments from flags (--flag)
for var in "$@"; do
  # If starts with "--" then assign it to a flag array
  if [[ $var == --* ]]; then
    count=1+${#flags[*]}
    flags[$count]=$var
    if [[ "$var" == "--script="* ]]; then
      script_position=$(expr 1 + ${#flags[*]})
    fi
    # Else assign to an arguments array
  else
    count=1+${#arguments[*]}
    arguments[$count]=$var
  fi
done

# Loop through flags and assign to variable. A flag "--email=austin@anchor.host" becomes $email
for i in "${!flags[@]}"; do

  # replace "-" with "_" and remove leading "--"
  flag_name=`echo ${flags[$i]} | cut -c 3-`

  # detected flag contains data
  if [[ $flag_name == *"="* ]]; then
    flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
    flag_name=`echo $flag_name | perl -n -e '/(.+?)=.+/&& print $1'` # extract name
    flag_name=${flag_name/-/_}
    declare "$flag_name"="$flag_value" # assigns to $flag_flagname
  else
    # assigns to $flag_flagname boolen
		flag_name=${flag_name//-/_}
    declare "$flag_name"=true
  fi

done

if [[ "$plugin" != "" ]]; then

	echo "Rolling back plugin $plugin"
	cd ~/Quicksaves/$domain/
	mkdir -p ~/Tmp/restore/$commit/
	git archive --format=zip $commit:plugins/$plugin/ > ~/Tmp/restore/$commit/$plugin.zip
	captaincore upload $website ~/Tmp/restore/$commit/$plugin.zip --public
	captaincore ssh $website --command="wp plugin install $plugin.zip --force --skip-plugins --skip-themes --skip-packages; rm $plugin.zip"
	rm -rf ~/Tmp/restore/$commit/

fi

if [[ "$theme" != "" ]]; then

	echo "Rolling back theme $theme"
	cd ~/Quicksaves/$domain/
	mkdir -p ~/Tmp/restore/$commit/
	git archive --format=zip $commit:themes/$theme/ > ~/Tmp/restore/$commit/$theme.zip
	captaincore upload $website ~/Tmp/restore/$commit/$theme.zip --public
	captaincore ssh $website --command="wp theme install $theme.zip --force --skip-plugins --skip-themes --skip-packages; rm $theme.zip"
	rm -rf ~/Tmp/restore/$commit/

fi

if [[ "$all" == "true" ]]; then

	echo "Rolling back entire quicksave"
	cd ~/Quicksaves/$domain/
	mkdir -p ~/Tmp/restore/$commit/
	git archive --format=zip $commit: > ~/Tmp/restore/$commit/quicksave_${commit}_all.zip
	captaincore upload $website ~/Tmp/restore/$commit/quicksave_${commit}_all.zip --public
	echo '<?php $upgrading = time(); ?>' | captaincore ssh $website --command="cat > .maintenance; rm -rf wp-content/themes/; unzip -o quicksave_${commit}_all.zip 'themes/*' -d wp-content/; rm -rf wp-content/plugins/; unzip -o quicksave_${commit}_all.zip 'plugins/*' -d wp-content/; rm -rf wp-content/mu-plugins/; unzip -o quicksave_${commit}_all.zip 'mu-plugins/*' -d wp-content/; rm .maintenance"
	rm -rf ~/Tmp/restore/$commit/

fi
