#!/usr/bin/env bash

#
#   Runs custom bash script or WP-CLI commands on a site.
#
#   `captaincore run <site> --code=<code>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ] && [[ "$code" != "" ]]; then
  # Generates receipe
  timestamp=$( date +'%Y-%m-%d' )
  recipe_file=$path_recipes/${captain_id}-${timestamp}-${code:0:8}.sh
  recipe_name=${timestamp}-${code:0:8}
  read -r -d '' php_code << heredoc
\$run_code = <<<PHPHEREDOC
$code
PHPHEREDOC;

echo base64_decode( \$run_code );
heredoc

  code=$( php -r "$php_code" )
  echo -n "$code" > "${recipe_file}"

  # Runs on specifed sites
  captaincore ssh ${arguments[*]} --recipe=$recipe_name --captain_id=$captain_id
fi

# Error if no sites specifed
if [ ${#arguments[*]} -eq 0 ] || [[ "$code" == "" ]]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a <site> and --code=<code>."
fi