#!/usr/bin/env bash

#
#   Fetch running processes
#
#   `captaincore running`
#
#   [<process-id>]
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

if [ ${#arguments[*]} -eq 1 ]; then
    php ${root_path}lib/local-scripts/track-progress.php ${path}/process-$1-progress.log
    inotifywait -q -m -e close_write -e delete_self ${path}/process-$1-progress.log | while read -r filename event; do
        if [[ "$event" == "DELETE_SELF" ]]; then
            kill $$
            exit
        fi
        php ${root_path}lib/local-scripts/track-progress.php $filename
    done
fi

if [ ${#arguments[*]} -eq 0 ]; then
  cat $path/running.json
fi
