#!/bin/bash

##
##		Creates Snapshot of website
##
## 		Pass arguments from command line like this
##		captaincore snapshot <site> --email=<email> --skip-remote
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

# Loop through arguments and separate regular arguments from flags (--flag)
for var in "$@"; do
	# If starts with "--" then assign it to a flag array
    if [[ $var == --* ]]
    then
    	count=1+${#flags[*]}
    	flags[$count]=$var
    # Else assign to an arguments array
    else
    	count=1+${#arguments[*]}
    	arguments[$count]=$var
    fi
done

# Loop through flags and assign to variable. A flag "--email=austin@anchor.host" becomes $email
for i in "${!flags[@]}"; do

	# replace "-" with "_" and remove leading "--"
	flag_name=`echo ${flags[$i]} | tr - _`
	flag_name=`echo $flag_name | cut -c 3-`

	# detected flag contains data
	if [[ $flag_name == *"="* ]]; then
	  flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
	  flag_name=`echo $flag_name | perl -n -e '/(.+)?=.+/&& print $1'` # extract name
	  declare "$flag_name"="$flag_value" # assigns to $flag_flagname
	else
	  # assigns to $flag_flagname boolen
	  declare "$flag_name"=true
	fi

done

snapshot_website() {

	if [ $# -gt 0 ]; then

		echo "Generating snapshots for $# sites"
		INDEX=1
		for website in "$@"; do

			domain=`captaincore site get $website --field=domain`

			## Return error if domain not found
			if [[ "$domain" == "" ]]; then
				echo "Can't locate website for install $website"
				return 1
			fi

			if [[ "$website" == *"-staging" ]]; then
				website=${website//-staging/}
				use_staging=true
			fi

			# Generate fresh backup
			captaincore backup $website

			## Generates snapshot archive
			timedate=$(date +%Y-%m-%d)
			cd ~/Backup/
			zip -r $domain-$timedate.zip $domain/ --exclude=$domain/_wpeprivate/\* --exclude=\*.git\* --exclude=$domain/wp-content/advanced-cache.php --exclude=$domain/wp-content/mu-plugins/mu-plugin.php --exclude=$domain/wp-content/mu-plugins/kinsta-mu-plugins.php --exclude=$domain/wp-content/mu-plugins/kinsta-mu-plugins/\* --exclude=$domain/wp-content/mu-plugins/slt-force-strong-passwords.php --exclude=$domain/wp-content/mu-plugins/force-strong-passwords/\* --exclude=$domain/wp-content/mu-plugins/wpengine-common/\*

			## Grab snapshot size in bytes
			if [[ "$OSTYPE" == "linux-gnu" ]]; then
			    ### Begin folder size in bytes without apparent-size flag
			    snapshot_size=`du -s --block-size=1 $path_tmp/$domain-$timedate.zip`
			    snapshot_size=`echo $snapshot_size | cut -d' ' -f 1`

			elif [[ "$OSTYPE" == "darwin"* ]]; then
			    ### Calculate folder size in bytes http://superuser.com/questions/22460/how-do-i-get-the-size-of-a-linux-or-mac-os-x-directory-from-the-command-line
			    snapshot_size=`find $path_tmp/$domain-$timedate.zip -type f -print0 | xargs -0 stat -f%z`
			fi

			if [[ $skip_remote != true ]]; then

				## Moves snapshot to Backblaze archive folder
				rclone move $domain-$timedate.zip $rclone_snapshot/$domain/

				## Post snapshot to ACF field
			  if [[ $captaincore_dev == true ]]; then
					curl -k --data-urlencode "storage=$snapshot_size" --data-urlencode "archive=$domain-$timedate.zip" --data-urlencode "email=$email" --data-urlencode "token=$token" "$captaincore_api/$domain/"
			  else
					curl --data-urlencode "storage=$snapshot_size" --data-urlencode "archive=$domain-$timedate.zip" --data-urlencode "email=$email" --data-urlencode "token=$token" "$captaincore_api/$domain/"
			  fi

			fi

			if [[ $delete_after_snapshot == true ]]; then
				echo "Removed files after snapshot"
				## Removed from rclone
				rclone config delete sftp-$website
				rclone config delete sftp-$website-staging
				## Removes directory from backup server
				rm -rf ~/Backup/$domain
			fi

			let INDEX=${INDEX}+1

		done

		fi
}

### See if any specific sites are selected
if [ $# -gt 0 ]; then
	## Run snapshots for sites
	snapshot_website $*
else
	# Run snapshots for all sites
	snapshot_website ${websites[@]}
fi
