#!/bin/bash

##
##      SSH batch wrapper for Kinsta and WP Engine
##
##      Runs command over SSH to all connected sites
##      captaincore ssh-batch "wp plugin list"
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

command=$1

# Loop through arguments and seperate regular arguments from flags (--flag)
for var in "$@"
do
	# If starts with "--" then assign it to a flag array
    if [[ $var == --* ]]
    then
    	count=1+${#flags[*]}
    	flags[$count]=$var
    # Else assign to an arguments array
    else
    	count=1+${#arguments[*]}
    	arguments[$count]=$var
    fi
done

# Loop through flags and assign to varible. A flag "--skip-dropbox" becomes $flag_skip_dropbox
for i in "${!flags[@]}"
do

	# replace "-" with "_" and remove leading "--"
	flag_name=`echo ${flags[$i]} | tr - _`
	flag_name=`echo $flag_name | cut -c 3-`

	# assigns to $flag_flagname
	declare "flag_$flag_name"=true

done

ssh_batch () {
if [ $# -gt 0 ]; then

	echo "SSH batch on $# websites"
	INDEX=1
	for website in "$@"; do

		### Load FTP credentials
		source $root_path/logins

    ### If subsite update stats and skip backup
    if [[ $subsite == "true" ]]; then

      echo "Skipping subsite $domain"
			return 1

    fi

		### Credentials found, start the backup
		if ! [ -z "$domain" ]; then

			captaincore ssh $website "$command"
			echo "Finished $domain"

		fi

		### Clear out variables
		domain=''
		username=''
		password=''
		ipAddress=''
		protocol=''
		port=''
		homedir=''
		remoteserver=''
    s3bucket=''
    s3path=''
    subsite=''

		let INDEX=${INDEX}+1
	done

fi
}

# Runs on all websites
ssh_batch ${websites[@]}
