#!/usr/bin/env bash

#
#   Generates and deploys Fathom tracker
#
#   `captaincore stats-deploy <site> <fathom-site-id>`
#
#   For multisite networks mutiple tracking codes can be WordPress passed in the following JSON format
#   '[{"domain":"site123.com","code":"ABCDE"},{"domain":"site346.com","code":"ABCDF"}]'
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

run_command() {

  site=$1
  id=$( echo $2 | sed 's/"/\\"/g')

  if [[ $site == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."
    return 1
  fi

  if [[ $id == "" ]]; then
    echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a fathom site id."
    return 1
  fi

  if [[ $tracker == "" ]]; then
    tracker=$captaincore_tracker
  fi

  captaincore ssh $site --script=deploy-fathom --tracker=$tracker --id="$id" --branding_author="$captaincore_branding_author" --branding_author_uri="$captaincore_branding_author_uri" --branding_slug=$captaincore_branding_slug

}
run_command ${arguments[*]}
