#!/usr/bin/env bash

#
#   Stats (Supports WordPress.com stats and selfhosted Fathom Analytics)
#
#   `captaincore stats <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

run_command() {

    site=$1

    # Load site configs
    eval $( captaincore site get $site --bash )

    if [[ "$fathom" != "" ]]; then
        captaincore stats-fetch $site fathom
    fi

    if [[ "$fathom" == "" ]]; then
        captaincore stats-fetch $site wordpress
    fi

}
run_command ${arguments[*]}