#!/usr/bin/env bash

#
#   Stats (Supports WordPress.com stats and selfhosted Fathom Analytics)
#
#   `captaincore stats <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

run_command() {

    site=$1
    if [[ "$site" == "" ]]; then
        echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a <site>."
        return
    fi

    # Extract environment and disgard stats from staging environments
    if [[ "$site" == *"-staging"* ]]; then
        printf "0"
        return
    fi

    # Load site configs
    eval $( captaincore site get $site --bash )

    if [[ "$fathom" != "" ]]; then
        captaincore stats-fetch $domain fathom
    fi

    if [[ "$fathom" == "" ]]; then
        captaincore stats-fetch $domain wordpress
    fi

}
run_command ${arguments[*]}