#!/usr/bin/env bash

#
#   Store zip to rclone remote for cold storage
#
#   `captaincore store-snapshot <url|file>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

zip=$1

run_command() {

	if [ -e $zip ]; then
		echo "Found local file $zip"
		rclone move $zip $rclone_archive -v
		return 1
	fi

	zip_filename=$( echo $zip | perl -n -e '/.+\/+(.+\.zip)/&& print $1' )
	wget -O $zip_filename $zip
	rclone move $zip_filename $rclone_archive -v

}

run_command
