#!/usr/bin/env bash

#
#   Sync website data for a single site.
#
#   `captaincore sync-data-runner <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	site=$1

	# Extract environment
	if [[ "$site" == *"-staging"* ]]; then
		environment=staging
	else
		environment=production
	fi

	# Load site configs
	while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain_id=$captain_id)"

	# Skip if not compatible
	if [[ $protocol != "sftp" ]] || [[ $site == "" ]]; then
		echo "Error: Can't SSH to $site";
		return 1
	fi

	# Remove leading "--" from flags
	for i in "${!flags[@]}"; do
		flags[$i]=`echo ${flags[$i]} | cut -c 3-`
	done

	cd ${root_path}data
	wp eval-file ../lib/local-scripts/site-sync-data.php site=$site environment=$environment ${flags[@]}

	if [[ "$skip_screenshot" != "true" ]]; then
    	captaincore screenshot ${site}-${environment} --captain_id=$captain_id
	fi
}

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ]; then
  # Runs on specifed sites
  run_command ${arguments[*]}
fi