#!/usr/bin/env bash

#
#   Sync website data
#
#   `captaincore sync-data`
#
#   [<site>...]
#   One or more sites.
#
#   [--all]
#   Sync website data for all sites.
#
#   [--parallel=<number-of-checks>]
#   Number of syncs at same time
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

	websites=$@

	# Assign default parallel if needed
  if [[ $parallel == "" ]]; then
    parallel=3
  fi

  # Generate random auth
  auth=''; for count in {0..6}; do auth+=$(printf "%x" $(($RANDOM%16)) ); done;

  # Begin time tracking
  log_date=$(date +'%Y-%m-%d')
  log_time=$(date +'%H-%M')

  # Define log file format
  log_file=$logs/${log_date}_${log_time}_$auth.txt
  echo "logging to $log_file"

  ( echo $websites | xargs -P $parallel -n 1 captaincore sync-data-runner ) 2>&1 | tee $log_file

}

# See if any sites are specifed
if [ ${#arguments[*]} -gt 0 ] && [[ $all != "true" ]]; then
  # Runs on specific sites
  run_command ${arguments[*]}
fi

# Runs on all sites
if [[ $all == "true" ]]; then
  echo "Sync website data on all sites"
	run_command ${websites[@]}
fi

# Error if no sites specifed
if [[ $all != "true" ]] && [ ${#arguments[*]} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify one or more sites, or use --all."
fi
