#!/bin/bash

#
#   Shows theme/plugin update logs
#
#   `captaincore update-fetch <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

site=$1

if [[ "$site" != "" ]]; then

	cd $path/$site/updates

	# Outputs json from all update files
	echo -n "["
	for file in *.json; do
		echo "{\"${file/.json}\":$(cat $file)},";
	done
	echo -n "]"

else

	echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."

fi
