#!/bin/bash

#
#   Shows theme/plugin update logs
#
#   `captaincore update-fetch <site>`
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config
source ${root_path}lib/arguments

website=$1

if [[ "$website" != "" ]]; then

	eval $(captaincore site get $website --bash)

	cd $path/${site}_${site_id}/updates

	# Outputs json from all update files
	json="["
	for file in *.json; do

		if [[ "$file" == *"-plugins.json" ]]; then
			type="plugins"
		fi
		if [[ "$file" == *"-themes.json" ]]; then
			type="themes"
		fi
		date=${file:0:17}
		json+="{\"date\":\"$date\",\"type\":\"$type\",\"updates\":$(cat $file)},";
	done
	json=${json%?}
	json+="]"

	echo "$json"

else

	echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a site."

fi
