#!/bin/bash

##
##      WP Engine SSH uploader
##
##      Uploads file to WP Engine install over ssh
##      captaincore upload anchorhost1 "~/Download/migration.zip" [--public]
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

website=$1

### Load FTP credentials
source $root_path/logins

# Loop through arguments and seperate regular arguments from flags (--flag)
for var in "$@"
do
	# If starts with "--" then assign it to a flag array
    if [[ $var == --* ]]
    then
    	count=1+${#flags[*]}
    	flags[$count]=$var
    # Else assign to an arguments array
    else
    	count=1+${#arguments[*]}
    	arguments[$count]=$var
    fi
done

# Loop through flags and assign to varible. A flag "--email=austin@anchor.host" becomes $email
for i in "${!flags[@]}"
do

	# replace "-" with "_" and remove leading "--"
	flag_name=`echo ${flags[$i]} | tr - _`
	flag_name=`echo $flag_name | cut -c 3-`

	# detected flag contains data
	if [[ $flag_name == *"="* ]]; then
	  flag_value=`echo $flag_name | perl -n -e '/.+?=(.+)/&& print $1'` # extract value
	  flag_name=`echo $flag_name | perl -n -e '/(.+)?=.+/&& print $1'` # extract name
	  declare "$flag_name"="$flag_value" # assigns to $flag_flagname
	else
	  # assigns to $flag_flagname boolen
	  declare "$flag_name"=true
	fi

done

### Credentials found, start the backup
if ! [ -z "$domain" ]
then

  ## If website on Kinsta then connect SSH using their format
  if [[ "$ipAddress" == *".kinsta.com" ]]; then

		if [ -n "$2" ]; then
			if [[ "$public" == "true" ]]; then
				scp -o StrictHostKeyChecking=no -P $port $2 $username@$ipAddress:public/
			else
				scp -o StrictHostKeyChecking=no -P $port $2 $username@$ipAddress:private/
			fi
		else
			echo 'Missing argument. Ex: captaincore upload anchorhost1 "~/Download/migration.zip'
		fi

  else ## If not Kinsta then try connecting using WP Engine's format
		echo "Uploading..."
		if [ -n "$2" ]; then
			if [[ "$public" == "true" ]]; then
		  	scp -o StrictHostKeyChecking=no -P 22 $2 $wpe_ssh_user+$1@$1.ssh.wpengine.net:sites/$1/
			else
				scp -o StrictHostKeyChecking=no -P 22 $2 $wpe_ssh_user+$1@$1.ssh.wpengine.net:sites/$1/_wpeprivate/
			fi
		else
		  echo 'Missing argument. Ex: captaincore upload anchorhost1 "~/Download/migration.zip'
		fi

  fi

else ## not recognized so attempt WP Engine's format

	if [ -n "$2" ]; then
		if [[ "$public" == "true" ]]; then
			scp -o StrictHostKeyChecking=no -P 22 $2 $wpe_ssh_user+$1@$1.ssh.wpengine.net:sites/$1/
		else
	  	scp -o StrictHostKeyChecking=no -P 22 $2 $wpe_ssh_user+$1@$1.ssh.wpengine.net:sites/$1/_wpeprivate/
		fi
	else
	  echo 'Missing argument. Ex: captaincore upload anchorhost1 "~/Download/migration.zip'
	fi

fi
