#!/usr/bin/env bash

#
#   Generates usage stats for one or more sites.
#
#   `captaincore usage-update <site>`
#

if [ ${#@} -ne 1 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify a <site>."
fi

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(php ${CAPTAINCORE_PATH}/lib/local-scripts/configs.php fetch)"

site=$1

run_command() {

  # Extract environment
  if [[ "$site" == *"-staging"* ]]; then
    environment=staging
  else
    environment=production
  fi
  
  # Load site configs
  IFS=$'\n'$'\r'; for line in $(captaincore site get $site --bash --captain-id=$CAPTAIN_ID); do declare "$line"; done

  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Begin folder size in bytes without apparent-size flag
    folder_size=`du -s --block-size=1 $path/${site}_${site_id}/${environment}/backup/`
    folder_size=`echo $folder_size | cut -d' ' -f 1`
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Calculate folder size in bytes http://superuser.com/questions/22460/how-do-i-get-the-size-of-a-linux-or-mac-os-x-directory-from-the-command-line
    if [ -d "$path/${site}_${site_id}/${environment}/backup/" ]; then
        folder_size=`find $path/${site}_${site_id}/${environment}/backup/ -type f -print0 | xargs -0 stat -f%z | awk '{b+=$1} END {print b}'`
      else
        folder_size=0
    fi
  fi

  # Views for yearly stats
  visits=$( captaincore stats $site-$environment --captain-id=$CAPTAIN_ID )

  cd ${CAPTAINCORE_PATH}/data
  wp eval-file ../lib/local-scripts/site-update-usage.php site=$site environment=$environment storage=$folder_size visits=$visits

}

run_command