#!/usr/bin/env bash

#
#   Share an archived file
#
#   `captaincore archive share <file>`
#

# Load configuration
while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(captaincore config fetch --captain-id=$CAPTAIN_ID)"

file="$1"

# Generate signed URL (7 day expiry) using rclone
rclone link "${rclone_archive}${file}" --expire 168h