#!/bin/bash

##
##      Preloading plugins to install
##
##      Pass arguments from command line like this
##      captaincore deploy plugins install1 install2
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

if [ $# -gt 0 ]
then
	echo "Loading specific sites"
	for (( i = 1; i <= $#; i++ ))
	do

		var="$i"
		website=${!var}

		### Load FTP credentials
		source $root_path/logins

		### Credentials found, start the backup
		if ! [ -z "$domain" ]
		then

			### Install standard set of plugins via WP-CLI
			captaincore ssh $website --command="wp plugin install akismet worker jetpack google-analytics-for-wordpress https://anchor.host/wp-content/plugins/gravityforms.zip https://anchor.host/wp-content/plugins/anchorhost-client.zip --force"

			### Loads token
			website_token=$(captaincore get token $domain)

			### Load dynamic list of plugins for install
			plugins=`captaincore generate plugins --token=$website_token --customers=$preloadusers`

			### Build plugin urls
			plugin_urls=()

			### Loop through dynamic list of plugins
			for plugin in $plugins; do
				plugin_urls+=("https://anchor.host/wp-content/plugins/${plugin}.zip")
			done

			### If plugin urls exist then install
			if [[ $plugin_urls != "" ]]; then
				echo "Installing $plugins";
				captaincore ssh $website --command="wp plugin install $plugin_urls"
			fi

		fi

		### Clear out variables
		domain=''
		username=''
		password=''
		ipAddress=''
		protocol=''
		port=''

	done

fi
