#!/bin/bash

##
##      Preloading plugins to site
##
##      Pass arguments from command line like this
##      captaincore deploy plugins <site>
##

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}config

if [ $# -gt 0 ]; then
	echo "Loading specific sites"
	for (( i = 1; i <= $#; i++ ))
	do

		var="$i"
		site=${!var}

		# Load site configs
		eval $(captaincore site get $site --bash)

		# Site found, start the backup
		if ! [ -z "$domain" ]
		then

			### Install standard set of plugins via WP-CLI
			captaincore ssh $site --command="wp plugin install akismet worker jetpack google-analytics-for-wordpress https://anchor.host/wp-content/plugins/gravityforms.zip https://anchor.host/wp-content/plugins/captaincore-client.zip --force"

			### Loads token
			website_token=$(captaincore get token $site)

			### Load dynamic list of plugins for site
			plugins=`captaincore plugins-get --token=$website_token --customers=$preloadusers`

			### Build plugin urls
			plugin_urls=()

			### Loop through dynamic list of plugins
			for plugin in $plugins; do
				plugin_urls+=("https://anchor.host/wp-content/plugins/${plugin}.zip")
			done

			### If plugin urls exist then install
			if [[ $plugin_urls != "" ]]; then
				echo "Installing $plugins";
				captaincore ssh $site --command="wp plugin install $plugin_urls"
			fi

		fi

		### Clear out variables
		domain=''
		username=''
		password=''
		address=''
		protocol=''
		port=''

	done

fi
