#!/bin/bash

##
##      Deploys custom preloading users mu-plugin to batch of installs
##
##      Pass arguments from command line like this
##      captaincore deploy users install1 install2
##
##      The users argument determines which json file to load user data from
##


# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source $root_path/config

generate_admin () {
for (( i = 1; i <= $#; i++ ))
do
    var="$i"
    website=${!var}

    if [[ $website == *"="* ]]
    then
      ## assume its a command and strip out the argument as the user group
      group=${website##*=}
    else
      ### Load FTP credentials
			eval $(captaincore site get $website --bash)

      ### Credentials found, start the backup
      if ! [ -z "$domain" ]
      then

        ### Loads token
        website_token=$(captaincore get token $domain)

        ### Generate JSON file based on preloaded list
        captaincore generate users-json --token=$website_token --customers=$preloadusers --website=$website

        ### Generate mu-plugin file based on a predefined user group
        captaincore generate users --install=$website --token=$website_token --customers=$preloadusers

        ### upload password plugin to mu-plugins
        rclone copy ~/Tmp/anchor_load_$website.php sftp-$website:$homedir/wp-content/mu-plugins/

        ### Trigger website to load password
        wget --no-cache --spider $ipAddress/wp-admin/
        sleep 1
        curl -Il $ipAddress/wp-login.php

        ## remove password plugin
        rclone delete sftp-$website:$homedir/wp-content/mu-plugins/anchor_load_$website.php

      fi

      ### Clear out variables
      domain=''
      username=''
      password=''
      ipAddress=''
      protocol=''
      port=''
    fi

done

}

### See if any specific sites are selected
if [ $# -gt 0 ]
then
    ## Run selected installs
    generate_admin $*
fi
