#!/bin/bash

##
##		Apply SSL using domain with www
##

domain=$(wp option get home)
domain=${domain/http:\/\/www./}
domain=${domain/https:\/\/www./}
domain=${domain/http:\/\//}
domain=${domain/https:\/\//}
wp search-replace http://$domain https://www.$domain --all-tables --skip-plugins --skip-themes
wp search-replace http://www.$domain https://www.$domain --all-tables --skip-plugins --skip-themes
wp cache flush
