#!/bin/bash

#
#   Update themes and plugins
#
#   update [--<field>=<value>]
#
#   OPTIONS
#   [--<field>=<value>]
#   : Extra arguments to pass to `wp theme update` and `wp plugin update`.
#   https://developer.wordpress.org/cli/commands/theme/update/
#   https://developer.wordpress.org/cli/commands/plugin/update/
#

# Pass through all arguments except script selector
arguments=${@/--script=update}

wp theme update $arguments
echo " "
wp plugin update $arguments
