#!/usr/bin/env bash

#
#   Fetches backups for a site
#
#   `captaincore site backup get <site> <backup-id>`
#

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(php ${CAPTAINCORE_PATH}/lib/local-scripts/configs.php fetch)"

if [ ${#@} -lt 2 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Please specify <site> and <backup-id>."
  exit
fi

site=$1
backup_id=$2

# Extract environment
if [[ "$site" == *"-staging"* ]]; then
    environment=staging
fi

if [[ "$site" == *"-production"* ]]; then
    environment=production
fi

if [[ "$site" != *"-"* ]]; then
    environment=production
fi

# Load site configs
while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain-id=$CAPTAIN_ID)"

backup_items="$path/${site}_${site_id}/${environment}/backups/snapshot-$backup_id.json"

if [ ! -f "$backup_items" ]; then
    captaincore backup get-generate $site-$environment $backup_id --captain-id=$CAPTAIN_ID
fi

cat $backup_items