#!/usr/bin/env bash

#
#   Fetches list of snapshots for a site from a backup repo
#
#   `captaincore backup list <site>`
#

if [ ${#@} -eq 0 ]; then
  echo -e "${COLOR_RED}Error:${COLOR_NORMAL} Requires a <site>"
  exit
fi

while read config; do
  if [[ "$config" == "Error:"* ]]; then
    continue
  fi
  declare "$config"
done <<< "$(php ${CAPTAINCORE_PATH}/lib/local-scripts/configs.php fetch)"

run_command() {

  site=$1

  # Extract environment
  if [[ "$site" == *"-staging"* ]]; then
    environment=staging
  fi

  if [[ "$site" == *"-production"* ]]; then
    environment=production
  fi

  if [[ "$site" != *"-"* ]]; then
    environment=production
  fi

  # Load site configs
  while read site_configs; do if [[ $site_configs == "" ]]; then continue; fi; declare "$site_configs"; done <<< "$(captaincore site get $site --bash --captain-id=$CAPTAIN_ID)"

  backup_list="$path/${site}_${site_id}/${environment}/backups/list.json"
  if [ ! -f "$backup_list" ]; then
    captaincore backup list-generate $site-$environment --captain-id=$CAPTAIN_ID
  fi
  cat "$backup_list"

}

run_command $@