#!/usr/bin/env bash

#
#   Get global configuration
#
#   `captaincore configuration get`
#
#   [--field=<field>]
#   Returns specific field
#
#   [--bash]
#   Return in bash format
#

# Load configuration
root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; root_path=${root_path%app*}
source ${root_path}lib/arguments

run_command() {

    cd ${root_path}data

    if [[ "$field" != "" ]]; then
        wp eval-file ${root_path}lib/local-scripts/configuration-get.php field=$field
        return
    fi

    wp eval-file ${root_path}lib/local-scripts/configuration-get.php

}
run_command ${arguments[*]}
